### ISSUE TITLE
failing sdp unit test

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1199]
```
test_simple_sdqp_inactive (__main__.SDPtests) ... ok

======================================================================
FAIL: test_example1 (__main__.SDPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sdp.py", line 534, in test_example1
    self.checkarray(sol_["x"],DMatrix([-1.1,-2.7375,-0.55]),digits=5)
  File "/home/ghorn/casadi_debian/casadi/test/python/helpers.py", line 192, in checkarray
    self.assertAlmostEqual(zt[i,j],zr[i,j],digits,"In %s: %s evaluation error.\n %s <->\n %s\n [digits=%d] at elem(%d,%d): " % (name,failmessage,str(zt),str(zr), digits, i,j, ))
  File "/home/ghorn/casadi_debian/casadi/test/python/helpers.py", line 146, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError: In :  evaluation error.
 [-1.1, -2.7375, -0.55] <->
 [-0.739806, -3.47899, -0.988986]
 [digits=5] at elem(0,0):  -1.1000000000000001e+00 <-> -7.3980636404211730e-01  scaled by 1

```

**Comment by jgillis** [comment]
Can you check if problem remains?

**Comment by jaeandersson** [comment]
No longer exists.
