### ISSUE TITLE
KNITRO errors

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1209]
The KNITRO interface is currently not tested as the tests are disabled in `nlp.py`.

When I enable the tests I get a lot of errors:
```
======================================================================
ERROR: testIPOPTdeg (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 857, in testIPOPTdeg
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "status<=0" on line 300 of file "/Users/janderss/dev/casadi/casadi/interfaces/knitro/knitro_interface.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTdegc (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 879, in testIPOPTdegc
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "status<=0" on line 300 of file "/Users/janderss/dev/casadi/casadi/interfaces/knitro/knitro_interface.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTinf (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 196, in testIPOPTinf
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "status==0" on line 271 of file "/Users/janderss/dev/casadi/casadi/interfaces/knitro/knitro_interface.cpp" failed. 
KTR_init_problem failed


======================================================================
ERROR: testIPOPTrb (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 219, in testIPOPTrb
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTrhb_gen (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 602, in testIPOPTrhb_gen
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTrhb_gen_par (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 701, in testIPOPTrhb_gen_par
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTrhb_gen_xnonfree (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 638, in testIPOPTrhb_gen_xnonfree
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: testIPOPTrhb_par (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 671, in testIPOPTrhb_par
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: test_IPOPTrhb (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 574, in test_IPOPTrhb
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: test_QP (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1049, in test_QP
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: test_pathological (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1428, in test_pathological
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: test_pathological2 (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1452, in test_pathological2
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
ERROR: test_pathological4 (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1503, in test_pathological4
    solver.evaluate()
  File "/Users/janderss/local/casadi/casadi_core.py", line 20023, in evaluate
    return _casadi_core.Function_evaluate(self, *args)
RuntimeError: The assertion "!isNull()" on line 110 of file "/Users/janderss/dev/casadi/casadi/core/shared_object.cpp" failed. 
Please notify the CasADi developers.


======================================================================
FAIL: testIPOPT (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 142, in testIPOPT
    self.assertAlmostEqual(solver.getOutput("g")[0],1,9,str(Solver))
  File "/Users/janderss/dev/casadi/test/python/helpers.py", line 146, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError: knitro 0.0000000000000000e+00 <-> 1.0000000000000000e+00  scaled by 1

======================================================================
FAIL: test_QP2 (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1134, in test_QP2
    self.assertAlmostEqual(solver.getOutput()[1],1.25,6,str(Solver))
  File "/Users/janderss/dev/casadi/test/python/helpers.py", line 146, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError: knitro 1.0393466998040535e+00 <-> 1.2500000000000000e+00  scaled by 1

======================================================================
FAIL: test_QP2_unconvex (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 1197, in test_QP2_unconvex
    self.assertAlmostEqual(solver.getOutput()[0],2.0/3,6,str(solver))
  File "/Users/janderss/dev/casadi/test/python/helpers.py", line 146, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError:  Inputs (NlpSolverInput: 8):
  0. (NLP_SOLVER_X0 aka 'x0')   2-by-1 (dense)
  1. (NLP_SOLVER_P aka 'p')   0-by-0 (dense)
  2. (NLP_SOLVER_LBX aka 'lbx')   2-by-1 (dense)
  3. (NLP_SOLVER_UBX aka 'ubx')   2-by-1 (dense)
  4. (NLP_SOLVER_LBG aka 'lbg')   3-by-1 (dense)
  5. (NLP_SOLVER_UBG aka 'ubg')   3-by-1 (dense)
  6. (NLP_SOLVER_LAM_X0 aka 'lam_x0')   2-by-1 (dense)
  7. (NLP_SOLVER_LAM_G0 aka 'lam_g0')   3-by-1 (dense)
 Outputs (NlpSolverOutput: 6):
  0. (NLP_SOLVER_X aka 'x')   2-by-1 (dense)
  1. (NLP_SOLVER_F aka 'f')   1-by-1 (dense)
  2. (NLP_SOLVER_G aka 'g')   3-by-1 (dense)
  3. (NLP_SOLVER_LAM_X aka 'lam_x')   2-by-1 (dense)
  4. (NLP_SOLVER_LAM_G aka 'lam_g')   3-by-1 (dense)
  5. (NLP_SOLVER_LAM_P aka 'lam_p')   0-by-0 (dense)
 3.3210346001021795e-01 <-> 6.6666666666666663e-01  scaled by 1

======================================================================
FAIL: test_activeLBX (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nlp.py", line 940, in test_activeLBX
    self.assertAlmostEqual(solver.getOutput("f")[0],9.0908263002590e-3,6,str(Solver))
  File "/Users/janderss/dev/casadi/test/python/helpers.py", line 146, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError: knitro 4.3817250416084281e+00 <-> 9.0908263002589997e-03  scaled by 1

----------------------------------------------------------------------
Ran 44 tests in 8.319s

FAILED (failures=4, errors=13)
```

**Comment by jaeandersson** [comment]
Closed since the unit test framework is no more.
