### ISSUE TITLE
Printing dictionary containing Function

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1260]
The following feature got exposed while refactoring ImplicitFunction, adding linear solver and Jacobian as options:
```
======================================================================
ERROR: testKINSol1c (__main__.NLPtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "implicitfunction.py", line 188, in testKINSol1c
    print solver.dictionary()
  File "/Library/Python/2.7/site-packages/casadi/casadi_core.py", line 2081, in dictionary
    return _casadi_core.OptionsFunctionality_dictionary(self, *args)
TypeError: GenericType not yet implemented
You have: ()
```

**Comment by jaeandersson** [comment]
Postpone to 2.3?

**Comment by jgillis** [comment]
This looks important enough to halt 2.2 for it

**Comment by jgillis** [comment]
Fix incoming
