### ISSUE TITLE
segfault in ipopt with pathological bounds

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1313]
I came across a segfault, and simplified it to this example:

```python
from casadi import *

x = SX.sym('x')

nlp = SXFunction(nlpIn(x=x), nlpOut(f=x**2))
nlp.init()

solver = NlpSolver('ipopt', nlp)
solver.setOption('linear_solver', 'ma86')
solver.init()

solver.setInput(inf, 'lbx')

solver.evaluate()
```
the output is
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.11.9, running with linear solver ma86.

eval_f failed:  on line 674 of file "/home/ghorn/casadi_debian/casadi/casadi/interfaces/ipopt/ipopt_interface.cpp"
IpoptInterface::f: NaN or Inf detected.


Number of Iterations....: 0
Segmentation fault
```
So i'm doing `minimize x^2 subject to inf <= x <= 0`, which is clearly infeasible. It shouldn't segfault though

**Comment by jaeandersson** [comment]
Stacktrace? Is it a CasADi bug or IPOPT bug?

**Comment by ghorn** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1575828 in Ipopt::IpoptApplication::call_optimize() () from /usr/lib/libipopt.so.1
(gdb) bt
#0  0x00007ffff1575828 in Ipopt::IpoptApplication::call_optimize() () from /usr/lib/libipopt.so.1
#1  0x00007ffff157936e in Ipopt::IpoptApplication::OptimizeNLP(Ipopt::SmartPtr<Ipopt::NLP> const&, Ipopt::SmartPtr<Ipopt::AlgorithmBuilder>&) () from /usr/lib/libipopt.so.1
#2  0x00007ffff15750aa in Ipopt::IpoptApplication::OptimizeNLP(Ipopt::SmartPtr<Ipopt::NLP> const&) () from /usr/lib/libipopt.so.1
#3  0x00007ffff156c175 in Ipopt::IpoptApplication::OptimizeTNLP(Ipopt::SmartPtr<Ipopt::TNLP> const&) () from /usr/lib/libipopt.so.1
#4  0x00007ffff19a802c in casadi::IpoptInterface::evaluate() () from /home/ghorn/casadi_install/lib/casadi/libcasadi_nlpsolver_ipopt.so
#5  0x00007ffff2e85065 in _wrap_Function_evaluate () from /home/ghorn/casadi_install/casadi/_casadi.so
#6  0x00000000004ccefc in PyEval_EvalFrameEx ()
#7  0x00000000004e6cf0 in ?? ()
#8  0x00000000005052e8 in ?? ()
#9  0x00000000004ce5f7 in PyEval_EvalFrameEx ()
#10 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#11 0x00000000004cc654 in PyEval_EvalFrameEx ()
#12 0x00000000004c94b9 in PyEval_EvalCodeEx ()
#13 0x0000000000503dff in ?? ()
#14 0x00000000004f9412 in PyRun_FileExFlags ()
#15 0x00000000004f8507 in PyRun_SimpleFileExFlags ()
#16 0x0000000000498ded in Py_Main ()
#17 0x00007ffff6f14b45 in __libc_start_main (main=0x498880 <main>, argc=2, argv=0x7fffffffe1e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe1d8)
    at libc-start.c:287
#18 0x00000000004987ab in _start ()
(gdb) 
```

**Comment by ghorn** [comment]
maybe just an ipopt issue

**Comment by jaeandersson** [comment]
I'd say we add a consistency check in the interface that lower bound has to be smaller or equal to upper bound. Plus maybe report to ipopt.

**Comment by jgillis** [comment]
I'd swear there was a consistency check already..
