### ISSUE TITLE
Segmentation fault while using casadi.mul for quadratic form

### ISSUE THREAD

**Issue by gmsanchez** [casadi/casadi#1465]
I am trying to learn to use CasADi since last week. I would like to build a Moving Horizon Estimator and a Model Predictive Controller. While trying to build the quadratic form for the objective function of these problems, I get a segmentation fault. Here's an example:

```
import sys
sys.path.append("/home/guiss/fun")
import numpy as np
import casadi
import casadi.tools as ctools

w = casadi.SX.sym("w",2,1)
Q = np.eye(2)
casadi.mul(w.T,Q,w)
```

Running gdb gives:

```
(gdb) run example.py
Starting program: /usr/bin/python example.py
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1e1b822 in casadi::SXElement::operator=(casadi::SXElement const&) ()
   from /home/guiss/fun/casadi/libcasadi.so
(gdb) bt
#0  0x00007ffff1e1b822 in casadi::SXElement::operator=(casadi::SXElement const&) () from /home/guiss/fun/casadi/libcasadi.so
#1  0x00007ffff2bd97db in void casadi::casadi_mm_sparse<casadi::SXElement>(casadi::SXElement const*, int const*, casadi::SXElement const*, int const*, casadi::SXElement*, int const*, casadi::SXElement*) ()
   from /home/guiss/fun/casadi/_casadi.so
#2  0x00007ffff2be3d33 in casadi::Matrix<casadi::SXElement>::zz_mtimes(casadi::Matrix<casadi::SXElement> const&, casadi::Matrix<casadi::SXElement> const&) const () from /home/guiss/fun/casadi/_casadi.so
#3  0x00007ffff2ac4f75 in _wrap_mul__SWIG_10.isra.2782 ()
   from /home/guiss/fun/casadi/_casadi.so
#4  0x00007ffff2b82fac in _wrap_mul () from /home/guiss/fun/casadi/_casadi.so
#5  0x00000000004d083b in PyEval_EvalFrameEx ()
#6  0x00000000004e7cc8 in ?? ()
#7  0x00000000004cf239 in PyEval_EvalFrameEx ()
#8  0x00000000004cb6b1 in PyEval_EvalCodeEx ()
#9  0x00000000004ce7d3 in PyEval_EvalFrameEx ()
#10 0x00000000004cb6b1 in PyEval_EvalCodeEx ()
#11 0x000000000050481f in ?? ()
#12 0x00000000004fc182 in PyRun_FileExFlags ()
#13 0x00000000004fb247 in PyRun_SimpleFileExFlags ()
#14 0x000000000049aa6e in Py_Main ()
#15 0x00007ffff7811a40 in __libc_start_main (main=0x49a500 <main>, argc=2, 
---Type <return> to continue, or q <return> to quit---
    argv=0x7fffffffdfb8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdfa8) at libc-start.c:289
#16 0x000000000049a429 in _start ()
(gdb) 
```
I am running current binary version of CasADi with numpy 1.8.2 from the Ubuntu 15.04 repositories. If you need some more data let me know.

Thanks in advance for any help.

**Comment by gmsanchez** [comment]
Looking at ```mhe_spring_damper.py``` I tried to change the NumPy matrix to DMatrix type, and it stopped giving the segmentation fault. However, I don't know if ```casadi.mul``` works correct. Here is another example:
```
import sys
sys.path.append("/home/guiss/fun/")
from casadi import *
import casadi.tools as ctools
import numpy as NP

Nw = 2
Nv = 1

x0 = np.array([[10.0], [5.0]])
w = casadi.SX.sym("w",Nw,1)

Q = 1.0*np.eye(Nw)
R = 1.0*np.eye(Nv)

_Q = casadi.DMatrix(Q)
_R = casadi.DMatrix(R)

l0 = casadi.SXFunction([w],[ctools.mul(w.T,w)])
l0.init()
l1 = casadi.SXFunction([w],[ctools.mul(w.T,_Q,w)])
l1.init()
l2 = casadi.SXFunction([w],[ctools.mul(ctools.mul(w.T,_Q),w)])
l2.init()


l0.setInput(x0)
l0.evaluate()
print l0.getOutput()

l1.setInput(x0)
l1.evaluate()
print l1.getOutput()

l2.setInput(x0)
l2.evaluate()
print l2.getOutput()
```
which gives the following
```
~$ python example1.py 
125
[20, 5]
125
```

Is it right to use ```casadi.mul``` the way I was trying to use it?

**Comment by gmsanchez** [comment]
I figured it out. I should have used ```ctools.mul((w.T,Q,w))```.

**Comment by jgillis** [comment]
Looks like a legit bug

**Comment by jgillis** [comment]
Stack trace with debug symbols:

```
0x00007ffff290ecc0 in casadi::SXElement::operator= (this=0x102daf8, scalar=...) at /home/jgillis/programs/casadi/casadi/core/sx/sx_element.cpp:96
96	    if (--node->count == 0) delete node;
(gdb) bt
#0  0x00007ffff290ecc0 in casadi::SXElement::operator= (this=0x102daf8, scalar=...) at /home/jgillis/programs/casadi/casadi/core/sx/sx_element.cpp:96
#1  0x00007ffff37afd0c in casadi::casadi_mm_sparse<casadi::SXElement> (x=0x105ce30, sp_x=0x103eac0, y=0x108e2d0, sp_y=0x10f8240, z=0x10a02a0, sp_z=0x103dcd0, w=0x102daf0)
    at /home/jgillis/programs/casadi/./casadi/core/sx/../matrix/../runtime/runtime.hpp:241
#2  0x00007ffff378240a in casadi::Matrix<casadi::SXElement>::zz_mtimes (this=0x102db30, y=..., z=...) at /home/jgillis/programs/casadi/./casadi/core/sx/../matrix/matrix_impl.hpp:1356
#3  0x00007ffff3797787 in casadi::mul (X=..., Y=..., Z=...) at /home/jgillis/programs/casadi/./casadi/core/sx/../matrix/sparsity_interface.hpp:594
#4  0x00007ffff36af0d0 in _wrap_mul__SWIG_10 (
    args=(<SX(this=<SwigPyObject at remote 0x7ffff1688420>) at remote 0x7ffff1681c10>, <numpy.ndarray at remote 0x105cdd0>, <SX(this=<SwigPyObject at remote 0x7ffff21e0450>) at remote 0x7ffff1681690>))
    at /home/jgillis/programs/casadi/build/swig/python/../casadiPYTHON_wrap.cxx:79836
#5  0x00007ffff36bdaa0 in _wrap_mul (self=0x0, 
    args=(<SX(this=<SwigPyObject at remote 0x7ffff1688420>) at remote 0x7ffff1681c10>, <numpy.ndarray at remote 0x105cdd0>, <SX(this=<SwigPyObject at remote 0x7ffff21e0450>) at remote 0x7ffff1681690>))
    at /home/jgillis/programs/casadi/build/swig/python/../casadiPYTHON_wrap.cxx:82962
#6  0x00000000004cde4b in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4343
#7  PyEval_EvalFrameEx () at ../Python/ceval.c:2718
```

From develop branch.
