### ISSUE TITLE
Make matrices non-iterable in Python

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1676]
The fact that "iterating over a matrix" is the same as iterating over the nonzeros gives rise to some unexpected results. For example, `min(DM.eye(3))` will return 1 (smallest nonzero) and not 0. It would be much cleaner if matrices could not be iterated over like this.

**Comment by jaeandersson** [comment]
The attempted fix triggers the following errors:
```
======================================================================
ERROR: test_structure_squared_dmatrix (__main__.Toolstests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools.py", line 477, in test_structure_squared_dmatrix
    a["x","y"] = 2
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 724, in __setitem__
    return self.struct.__setitem__(self.prefix + powerIndex,data)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 637, in __setitem__
    SetterDispatcher(struct=self.struct,master=self.master,mtype=self.mtype),payload=value)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 341, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 208, in traverseByPowerIndex
    return dispatcher(payload,canonicalIndex,extraIndex=tuple(powerIndex),entry=self)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 589, in __call__
    i = performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 665, in performExtraIndex
    a = delegation(a,entry,0)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 646, in delegation
    return extraIndex(entry.shapestruct[i])
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 1331, in __call__
    return struct.f.__getitem__(self.arg)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 811, in __getitem__
    return vec(self.struct.traverseByPowerIndex(powerIndex,dispatcher=CasadiStructure.FlatIndexDispatcher(struct=self.struct)))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 341, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 204, in traverseByPowerIndex
    return dispatcher(payload,canonicalIndex,entry=self)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 754, in __call__
    return list(performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry))
  File "/Users/jaeandersson/local/casadi/casadi.py", line 7312, in __getitem__
    return self.get(False, s)
  File "/Users/jaeandersson/local/casadi/casadi.py", line 6436, in get
    return _casadi.IM_get(self, *args)
Exception: Error occured in struct context with powerIndex ('t', 'x', 'y'), at canonicalIndex ():
Error occured in entry context with powerIndex ('x', 'y'), at canonicalIndex ('t',):
Error occured in struct context with powerIndex ('x',), at canonicalIndex ():
Error occured in entry context with powerIndex (), at canonicalIndex ('x',):
The assertion "stop<=len" on line 63 of file "/Users/jaeandersson/dev/casadi/casadi/core/slice.cpp" failed.
Slice (start=1, stop=2, step=1) out of bounds with supplied length of 1

======================================================================
ERROR: test_structure_squared_repeated_dmatrix (__main__.Toolstests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools.py", line 491, in test_structure_squared_repeated_dmatrix
    self.checkarray(a[0,"x","y"],DM([2]))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 720, in __getitem__
    return self.struct.__getitem__(self.prefix + powerIndex)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 631, in __getitem__
    return self.struct.traverseByPowerIndex(powerIndex,dispatcher=GetterDispatcher(struct=self.struct,master=self.master,priority_object_map=self.priority_object_map))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 341, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 227, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 208, in traverseByPowerIndex
    return dispatcher(payload,canonicalIndex,extraIndex=tuple(powerIndex),entry=self)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 568, in __call__
    i = performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 665, in performExtraIndex
    a = delegation(a,entry,0)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 646, in delegation
    return extraIndex(entry.shapestruct[i])
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 1331, in __call__
    return struct.f.__getitem__(self.arg)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 811, in __getitem__
    return vec(self.struct.traverseByPowerIndex(powerIndex,dispatcher=CasadiStructure.FlatIndexDispatcher(struct=self.struct)))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 341, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 204, in traverseByPowerIndex
    return dispatcher(payload,canonicalIndex,entry=self)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 754, in __call__
    return list(performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry))
  File "/Users/jaeandersson/local/casadi/casadi.py", line 7312, in __getitem__
    return self.get(False, s)
  File "/Users/jaeandersson/local/casadi/casadi.py", line 6436, in get
    return _casadi.IM_get(self, *args)
Exception: Error occured in struct context with powerIndex ('t', 0, 'x', 'y'), at canonicalIndex ():
Error occured in entry context with powerIndex (0, 'x', 'y'), at canonicalIndex ('t',):
Error occured in entry context with powerIndex ('x', 'y'), at canonicalIndex ('t', 0):
Error occured in struct context with powerIndex ('x',), at canonicalIndex ():
Error occured in entry context with powerIndex (), at canonicalIndex ('x',):
The assertion "stop<=len" on line 63 of file "/Users/jaeandersson/dev/casadi/casadi/core/slice.cpp" failed.
Slice (start=1, stop=2, step=1) out of bounds with supplied length of 1


======================================================================
ERROR: test_symm (__main__.Toolstests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools.py", line 546, in test_symm
    self.checkarray(b["P",["x","z"],["x","z"]] ,DM([[0,6],[6,8]]))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 631, in __getitem__
    return self.struct.traverseByPowerIndex(powerIndex,dispatcher=GetterDispatcher(struct=self.struct,master=self.master,priority_object_map=self.priority_object_map))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 341, in traverseByPowerIndex
    payload=payload
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 208, in traverseByPowerIndex
    return dispatcher(payload,canonicalIndex,extraIndex=tuple(powerIndex),entry=self)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 568, in __call__
    i = performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 665, in performExtraIndex
    a = delegation(a,entry,0)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 646, in delegation
    return extraIndex(entry.shapestruct[i])
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 1331, in __call__
    return struct.f.__getitem__(self.arg)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 109, in proper
    return f(self,mbt,*args)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 811, in __getitem__
    return vec(self.struct.traverseByPowerIndex(powerIndex,dispatcher=CasadiStructure.FlatIndexDispatcher(struct=self.struct)))
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 411, in traverseByPowerIndex
    for i,s in enumerate(p)]
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 334, in traverseByPowerIndex
    if len(powerIndex)==0: return dispatcher(payload,canonicalIndex)
  File "/Users/jaeandersson/local/casadi/tools/structure.py", line 754, in __call__
    return list(performExtraIndex(self.struct.map[canonicalIndex],extraIndex=extraIndex,entry=entry))
  File "/Users/jaeandersson/local/casadi/casadi.py", line 7312, in __getitem__
    return self.get(False, s)
  File "/Users/jaeandersson/local/casadi/casadi.py", line 6436, in get
    return _casadi.IM_get(self, *args)
Exception: Error occured in struct context with powerIndex ('P', ['x', 'z'], ['x', 'z']), at canonicalIndex ():
Error occured in entry context with powerIndex (['x', 'z'], ['x', 'z']), at canonicalIndex ('P',):
Error occured in struct context with powerIndex (['x', 'z'],), at canonicalIndex ():
Error occured in struct context with powerIndex (), at canonicalIndex ('x',):
The assertion "stop<=len" on line 63 of file "/Users/jaeandersson/dev/casadi/casadi/core/slice.cpp" failed.
Slice (start=1, stop=2, step=1) out of bounds with supplied length of 1

```
