### ISSUE TITLE
Integrator + OpenMP parallelization = SIGSEGV

### ISSUE THREAD

**Issue by mkatliar** [casadi/casadi#1737]
Example:

``` python
import casadi as cs

q = cs.MX.sym('q')
v = cs.MX.sym('v')
u = cs.MX.sym('u')

x = cs.vertcat(q, v)
dx = cs.vertcat(v, u)

i = cs.integrator('Integrator', 'cvodes', {'x' : x, 'p' : u, 'ode' : dx})

N = 100
x_val = cs.DM.zeros(2, N)
u_val = cs.DM.zeros(1, N)
i_par = i.map('Integrator_map', 'openmp', N)

out = i_par(x0 = x_val, p = u_val)
```

Results in

```
Program received signal SIGSEGV, Segmentation fault.
```

Stack trace at the crash point:

```
0x00007ffff1b98d70 in casadi::Integrator::set_temp(void*, double const**, double**, int*, double*) const () from /usr/local/lib/libcasadi.so.3.0
(gdb) bt
#0  0x00007ffff1b98d70 in casadi::Integrator::set_temp(void*, double const**, double**, int*, double*) const () from /usr/local/lib/libcasadi.so.3.0
#1  0x00007ffff1b2ceab in casadi::FunctionInternal::setup(void*, double const**, double**, int*, double*) const () from /usr/local/lib/libcasadi.so.3.0
#2  0x00007ffff1b99a8f in casadi::Integrator::eval(void*, double const**, double**, int*, double*) const () from /usr/local/lib/libcasadi.so.3.0
#3  0x00007ffff1be86fe in casadi::MapOmp::eval(void*, double const**, double**, int*, double*) const [clone ._omp_fn.0] () from /usr/local/lib/libcasadi.so.3.0
#4  0x00007ffff2f4949e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#5  0x00007ffff7bc26aa in start_thread (arg=0x7ffff06c9700) at pthread_create.c:333
#6  0x00007ffff78f7e9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

If 'openmp' is changed to 'serial', everything is fine.

**Comment by jaeandersson** [comment]
This is actually to be expected. IIRC, MapOmp currently does not handle multiple memory objects correctly. This is only a an issue for Function that allocate persistent memory objects, like CVODES above. Or if you'd try to do a map on an NLP solver.

**Comment by jgillis** [comment]
This was fixed a while ago in develop
