### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by abuzouz** [casadi/casadi#1933]
**I named my binary file casadiinstalldir just as the instructions do. I also made sure the binary and my version of spyder (Python 2.7) are both 2.7. I tested out the installation in the editor:**
import sys
sys.path.append(r"casadiinstalldir")
from casadi import *
x = MX.sym("x")
print jacobian(sin(x),x)

**And I keep getting the following error:**
runfile('C:/Users/CE-je1714/Documents/Research Casadi/casadiinstalldir/temp.py', wdir='C:/Users/CE-je1714/Documents/Research Casadi/casadiinstalldir')
Traceback (most recent call last):

  File "<ipython-input-3-a83ba274f3ee>", line 1, in <module>
    runfile('C:/Users/CE-je1714/Documents/Research Casadi/casadiinstalldir/temp.py', wdir='C:/Users/CE-je1714/Documents//Research Casadi/casadiinstalldir')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/CE-je1714/Documents/Research Casadi/casadiinstalldir/temp.py", line 3, in <module>
    from casadi import *

  File "casadi.py", line 21, in <module>
    _casadi = swig_import_helper()

  File "casadi.py", line 20, in swig_import_helper
    return importlib.import_module('_casadi')

  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)

ImportError: DLL load failed: %1 is not a valid Win32 application.

**What am I missing?**

**Comment by jgillis** [comment]
I'm not sure about this one.
Could you try the following: 

sys.path.append(r"C:/Users/CE-je1714/Documents/Research Casadi/casadiinstalldir/")

**Comment by jgillis** [comment]
Closing for lack of response; please repost on the forum if you still have this difficulty
