### ISSUE TITLE
Missing error or feature for nlpsol with missing parameter

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2086]
```python
from casadi import *

x = MX.sym("x")
p = MX.sym("p")

# We should either make this line fail with a friendly error,
solver = nlpsol("solver","ipopt",{"x":x,"f":(x-p)**2}, dict(verbose=True))

ret = solver(x0=x)

f = Function('solver',[x,p],[ret["x"]])

# or make this output '2', and make `solver(x0=0)` fail
print(f(2, 2))
```

These are really tricky bugs to hunt down...

Related to #2028

EDIT(@jaeandersson): Changed "nlpsol" to "ipopt", fixed evaluation syntax.

**Comment by jgillis** [comment]
ping @jaeandersson

**Comment by jaeandersson** [comment]
I get:
```RuntimeError: .../casadi/core/plugin_interface.hpp:387: Plugin 'nlpsol' is not found.```
What do you get?

**Comment by jaeandersson** [comment]
Ah, I see what you mean now

**Comment by jgillis** [comment]
Thx for fixing the typo

**Comment by jaeandersson** [comment]
Fixed

**Comment by jaeandersson** [comment]
Error message now:
```
Traceback (most recent call last):
  File "bug_2086.py", line 8, in <module>
    solver = nlpsol("solver","ipopt",{"x":x,"f":(x-p)**2}, opts)
  File "/Users/jaeandersson/local/python/casadi/casadi.py", line 14182, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/nlpsol.cpp:96: Cannot create NLP oracle since [p] are free.
```
