### ISSUE TITLE
matlab crashes

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2114]
Fails in matlab:
```matlab
y=MX.sym('y')
expm_const(speye(4),y/5)
```

Works in python:
```python
y=MX.sym('y')
expm_const(DM.eye(4),y/5)
```

Walking with gdb exposes an (ancient) not-implemented error in SubAssign.
Stack involves `~MXNode`. MXNode-constructor-raising-error + new MXNode destructor problem?

```
#0  0x00007fff6a184e1b in casadi::SubAssign::SubAssign (this=0x7fff5cbe0f40, x=..., y=..., i=..., j=...) at /home/jgillis/programs/casadi/casadi/core/subassign.cpp:34
#1  0x00007fff6a1369f3 in casadi::MXNode::get_subassign (this=0x7fff5cbe1330, y=..., i=..., j=...) at /home/jgillis/programs/casadi/casadi/core/mx_node.cpp:499
#2  0x00007fff52a5e8bf in casadi::MX::project (x=..., sp=..., intersect=false) at /home/jgillis/programs/casadi/casadi/core/mx.cpp:745
#3  0x00007fff52a7cd53 in casadi::project (A=..., sp=..., intersect=false) at /home/jgillis/programs/casadi/casadi/core/generic_matrix.hpp:454
#4  0x00007fff52acc6dc in casadi::Call::projectArg (x=..., sp=..., i=0) at /home/jgillis/programs/casadi/casadi/core/casadi_call.cpp:37
#5  0x00007fff52accf53 in casadi::Call::Call (this=0x7fff5cbde9e0, fcn=..., arg=...) at /home/jgillis/programs/casadi/casadi/core/casadi_call.cpp:69
#6  0x00007fff52ace483 in casadi::Call::create (fcn=..., arg=...) at /home/jgillis/programs/casadi/casadi/core/casadi_call.cpp:207
#7  0x00007fff52b33d37 in casadi::FunctionInternal::eval_mx (this=0x7fff5cbe1620, arg=..., res=..., always_inline=false, never_inline=false) at /home/jgillis/programs/casadi/casadi/core/function_internal.cpp:1532
#8  0x00007fff6a1ac65a in casadi::FunctionInternal::call_gen (this=0x7fff5cbe1620, arg=..., res=..., always_inline=false, never_inline=false) at /home/jgillis/programs/casadi/casadi/core/function_internal.hpp:163
#9  0x00007fff6a1af767 in casadi::FunctionInternal::call<casadi::MX> (this=0x7fff5cbe1620, arg=..., res=..., always_inline=false, never_inline=false) at /home/jgillis/programs/casadi/casadi/core/function_internal.hpp:840
#10 0x00007fff6a19846c in casadi::Function::call (this=0x7fffda885350, arg=..., res=..., always_inline=false, never_inline=false) at /home/jgillis/programs/casadi/casadi/core/function.cpp:307
#11 0x00007fff6a1a4d8c in casadi::Function::operator() (this=0x7fffda885350, arg=...) at /home/jgillis/programs/casadi/casadi/core/function.cpp:1049
#12 0x00007fff6a117294 in casadi::MX::expm_const (A=..., t=...) at /home/jgillis/programs/casadi/casadi/core/mx.cpp:1714
#13 0x00007fff6abb5087 in casadi::expm_const (A=..., t=...) at /home/jgillis/programs/casadi/./casadi/core/generic_matrix.hpp:566
#14 0x00007fff6aa07488 in casadi_GenericMatrixCommon_casadi_expm_const__SWIG_0 (A=..., t=...) at /home/jgillis/programs/casadi/build-matlab/swig/casadiMATLAB_wrap.cxx:5180
#15 0x00007fff6aa55095 in _wrap_GenericMatrixCommon_expm_const__SWIG_0 (resc=1, resv=0x7fffda885c18, argc=2, argv=0x7fff5cbde6d8) at /home/jgillis/programs/casadi/build-matlab/swig/casadiMATLAB_wrap.cxx:28119
#16 0x00007fff6aa79418 in _wrap_GenericMatrixCommon_expm_const (resc=1, resv=0x7fffda885c18, argc=2, argv=0x7fff5cbde6d8) at /home/jgillis/programs/casadi/build-matlab/swig/casadiMATLAB_wrap.cxx:36832
```

related crash
```matlab
y=MX.sym('y')
P = expm_const(eye(4),y/5)
P(1:2,1:2);
```

**Comment by jgillis** [comment]
Not crashing in e8765164e

**Comment by jaeandersson** [comment]
Could it be slicot?

**Comment by jgillis** [comment]
I'm debugging

**Comment by jgillis** [comment]
Offending commits are a1f1c9ed6d2281009f3e1469a414a8ca6952a7e4 + 2331f45c99d204fe3a537c7afa837de55973a51d

**Comment by jgillis** [comment]
Was chasing ghosts; unclean build.
