### ISSUE TITLE
struct_MX.cat raises an exception if there is a row-vector entry

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#2180]
Example:

```python
import casadi as cs
import casadi.tools as ct


s = ct.struct_MX([
    ct.entry('x', expr=cs.MX.zeros(1, 3)),
    ct.entry('y', expr=cs.MX.zeros(2, 4))
])

s.cat  # ERROR
```

Output:
```
untimeError, .../casadi/core/mx.cpp:947: Assertion "ne[i].size2()==ne[0].size2()" failed:
vertcat dimension mismatch  x[1]:8x1 and x[0]: 1x3.
Traceback (most recent call last):
  File "/home/mkatliar/projects/Heli_MPC/bug.py", line 10, in <module>
    s.cat
  File "/usr/local/python/casadi/tools/structure3.py", line 859, in cat
    if isinstance(self.master,DataReference):
  File "/usr/local/python/casadi/tools/structure3.py", line 1103, in master
    self.master_cached = vertcat(*[i.nz[:] for i in self.storage])
  File "/usr/local/python/casadi/casadi.py", line 348, in vertcat
    def vertcat(*args): return _vertcat(args)
  File "/usr/local/python/casadi/casadi.py", line 10970, in _vertcat
    return _casadi._vertcat(*args)
RuntimeError: .../casadi/core/mx.cpp:947: Assertion "ne[i].size2()==ne[0].size2()" failed:
vertcat dimension mismatch  x[1]:8x1 and x[0]: 1x3.
```

The expression `[i.nz[:] for i in self.storage]` in `structure3.py` evaluates to
```
[MX(zeros(1x3)), MX(zeros(8x1))]
```

The 0th element of the list is a row vector, which cannot be vertically concatenated with the column vector. The row-vector is produced because of #2179.

**Comment by jgillis** [comment]
Merged workaround; good enough until #1388
