### ISSUE TITLE
Callback Function to Define Manually Jacobians Only Compatible with Casadi 3.1.1

### ISSUE THREAD

**Issue by lukasbrnst** [casadi/casadi#2266]
Hi!
I want to report a compatibility problem concerning Callback functionality.
I implemented a minimization problem (nlp) using IPOPT and including Callback functions to define manually jacobians.
After reinstalling ubuntu 16.04, python 3.6 (Anaconda) and casadi (conda) the code raised an error.
I tested the code with all available conda-forge casadi versions (3.1.1, 3.2.2, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3), but **only 3.1.1 worked**.
I also tried to run an example code (from https://github.com/casadi/casadi/issues/1854), but the same error has been raised.

In the following zippet I have a minimal example:
```python
from casadi import *

class testfunj(Callback):
    """Jacobian class for 'testfun'. Class-functions are overloaded from casadi"""
    def __init__(self, name, opts={}):
        Callback.__init__(self)
        self.construct(name, opts)

    def init(self):
        print('initialising object')

    def get_n_in(self): return 1

    def get_n_out(self): return 2

    def get_sparsity_in(self, n_in):
        return Sparsity.dense(1, 1)

    def get_sparsity_out(self, n_out):
        return Sparsity.dense(1, 1)

    def eval(self, arg):
        x = arg[0]
        f = -2 * x + 3
        jac = -2
        return [jac, f]

    def has_jacobian(self): return True

    def get_jacobian(self, name, opts):
        x = MX.sym('x',1,1)
        return Function('jacobian', [x], [vertcat(DM.eye(1),DM(1,1))])


class testfun(Callback):
    """Basic class to call within the optimization."""
    def __init__(self, name, opts={}):
        #self.cnt = construct_reference_polyline(path)
        Callback.__init__(self)
        self.construct(name, opts)


    def get_n_in(self): return 1
    def get_n_out(self): return 1

    def get_sparsity_in(self, n_in):
        return Sparsity.dense(1, 1)

    def get_sparsity_out(self, n_out):
        return Sparsity.dense(1, 1)

    def init(self):
        self.low_level = testfunj('low_level')

    def eval(self, arg):
        [jac, f] = self.low_level(arg[0])
        return [f]

    def has_jacobian(self): return True

    def get_jacobian(self, name, opts):
        x = MX.sym('x',1,1)
        [jacSym, f] = self.low_level(x)
        return Function('jacobian', [x], [jacSym])



f1 = testfun("f1")
print(f1(0))


x = MX.sym("x")
y = MX.sym("y")
w = [x,y]
w0 = [0,0]

ubw = [5,4]
lbw = [0,0]

g = [f1(x)-y]
lbg = [0]
ubg = [0]

g += [2*x + 1 -y]
lbg += [0]
ubg += [0]

nlp = {'x': vertcat(*w), 'f':y, 'g':vertcat(*g)}

options = {}

solver = nlpsol('solver', "ipopt", nlp, options)
sol = solver(x0=vertcat(*w0),lbg=vertcat(*lbg),ubg=vertcat(*ubg), lbx=vertcat(*lbw), ubx=vertcat(*ubw))

print(sol['f'])
print(sol['x'])
```
When running this script the following error raises:
```
/home/lukas/anaconda3/bin/python /home/lukas/.PyCharmCE2018.1/config/scratches/scratch_5.py
initialising object
TypeError: get_jacobian() takes 3 positional arguments but 5 were given
Traceback (most recent call last):
  File "/home/lukas/.PyCharmCE2018.1/config/scratches/scratch_5.py", line 90, in <module>
    solver = nlpsol('solver', "ipopt", nlp, options)
  File "/home/lukas/anaconda3/lib/python3.6/site-packages/casadi/casadi.py", line 9593, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/function_internal.cpp:123: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1451:
Failed to create nlp_grad:[x, p, lam:f, lam:g]->[f, g, grad:gamma:x, grad:gamma:p] with {"gamma": [f, g]}:
.../casadi/core/factory.hpp:346: Gradient generation failed:
Error in MX::gradient at .../casadi/core/generic_matrix.hpp:1192:
Error in MX::jtimes at .../casadi/core/generic_matrix.hpp:1181:
Error in MX::reverse at .../casadi/core/mx.cpp:1676:
Error in MXFunction::ad_reverse at .../casadi/core/mx_function.cpp:997:
Error in MX::ad_reverse for node of type N6casadi4CallE at .../casadi/core/mx.cpp:1860:
Error in Call::ad_reverse for 'f1' [CallbackInternal] at .../casadi/core/casadi_call.cpp:146:
.../casadi/core/callback_internal.cpp:117: Error calling "get_jacobian" for object f1:
/feedstock_root/build_artefacts/casadi_1523461497281/work/casadi-3.4.1/build/swig/casadiPYTHON_wrap.cxx:3730: get_jacobian() takes 3 positional arguments but 5 were given

Process finished with exit code 1
```

Does anybody have an idea why this code is not downwards compatible?

Best Regards,
Lukas Braunstorfer.

**Comment by jaeandersson** [comment]
Providing derivative information with Callback instances is not really stable and the API is very much in flux. The up-to-date for each CasADi version can probably be found in <casadi_root>/test/python/function.py.

Current syntax is:
```python
        def get_jacobian(self, name, inames, onames, opts):
          x = SX.sym("x")
          y = SX.sym("y")
          out_g = SX.sym('out_g', Sparsity(1,1))
          J = Function(name, [x,y,out_g],[horzcat(cos(x+3*y),3*cos(x+3*y))], inames, onames, opts)
          return J
```
I.e., the get_jacobian function take a list of input names (inames) and output names (onames).

The return function also has an entry for the non-differentiated output, entering as an input, here out_g. An all-zero-sparsity (as here) denote that there is indeed no such dependency, but it must still be included in the return object.

Unfortunately, there are more changes to this functionality yet to come. In particular, the signature of the output of the return object will change to include a separate output for each Jacobian block. After that, hopefully the API will be more or less stable.

Make sure you only use Callback if you absolutely need to - it's as I said a feature under development. It also comes with large penalties in terms of speed.

**Comment by jgillis** [comment]
Please re-open on our forum if this is not resolved yet.
