### ISSUE TITLE
Modelica to CasADi

### ISSUE THREAD

**Issue by yfuerst** [casadi/casadi#2268]
I want to use Modelica for modelling purposes and transfer the model to CasADi. In the documentation I found the file `thermodynamics_example.py` in `casadi/docs/examples/python/modelica/fritzson_application_examples` explaining the procedure. Apparently the function `compile_jmu` is not available anymore in JModelica. Does anyone know how to fix this issue? Is there another possibility to transfer Modelica code to CasADi?

**Comment by vruge** [comment]
Can you try if `compile_fmux` is available, please?
````python
from pymodelica import compile_fmux
````

**Comment by yfuerst** [comment]
I am using JModelica 2.0. It is available, but throws the exception
```JError: Unknown tag: XML_vendorAnnotations
java.lang.RuntimeException: Unknown tag: XML_vendorAnnotations
	at org.jmodelica.optimica.compiler.AbstractGenerator.getTag(Unknown Source)
	at org.jmodelica.optimica.compiler.AbstractGenerator.generate(Unknown Source)
	at org.jmodelica.optimica.compiler.GenericXMLGenerator.generate(Unknown Source)
	at org.jmodelica.optimica.compiler.AbstractGenerator.generate(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.generateFile(Unknown Source)
	at org.jmodelica.optimica.compiler.Templates.generateXMLFiles(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.doGenerateCode(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.generateCode(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.doCompileModel(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.compileModel(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.doCompileUnit(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.compileUnit(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.compileUnit(Unknown Source)
	at org.jmodelica.optimica.compiler.ModelicaCompiler.compileModelFromCommandLine(Unknown Source)
	at org.jmodelica.optimica.compiler.OptimicaCompiler.main(Unknown Source)
```

**Comment by vruge** [comment]
Great!

with fmux(I guess x for xml) additional arguments for xml generation are not need.
```python
from pymodelica import compile_fmux

compile_fmux('BasicVolumeMassConservation', my_casad_path + 'docs/examples/python/modelica/fritzson_application_examples/thermodynamics_example.mo")
```
should work.

**Comment by yfuerst** [comment]
I guess my last comment was not very clear. My minimal working example looks like this
```python
import os
import sys
import numpy as NP
from numpy import *
import matplotlib.pyplot as plt
import zipfile
import time
import shutil

try:
    # JModelica
    from pymodelica import compile_fmux
    use_precompiled = False
except:
    print("No jmodelica installation, falling back to precompiled XML-files")
    use_precompiled = True

# CasADi
from casadi import *

def comp(name):
    curr_dir = os.path.dirname(os.path.abspath("__file__"))
    if use_precompiled:
        shutil.copy(curr_dir + '/precompiled_' + name + '.xml', name + '.xml')
    else:
        jmu_name = compile_fmux(name, curr_dir+"/thermodynamics_example.mo")
        modname = name.replace('.','_')
        sfile = zipfile.ZipFile(curr_dir+'/'+modname+'.jmu','r')
        mfile = sfile.extract('modelDescription.xml','.')
        os.remove(modname+'.jmu')
        os.rename('modelDescription.xml',modname+'.xml')

comp("BasicVolumeMassConservation")
```
and is basically the same as in `thermodynamics_example.py`. I simply changed the model compilation to `compile_fmux(name, curr_dir+"/thermodynamics_example.mo")` like you suggested. The call of `compile_fmux` throws this exception and I have no idea what to do. Looks like a compiler problem to me.
```
JErrorTraceback (most recent call last)
<ipython-input-6-bbcccd936aaf> in <module>()
----> 1 comp("BasicVolumeMassConservation")

<ipython-input-5-461f25686acb> in comp(name)
      4         shutil.copy(curr_dir + '/precompiled_' + name + '.xml', name + '.xml')
      5     else:
----> 6         jmu_name = compile_fmux(name, curr_dir+"/thermodynamics_example.mo")
      7         modname = name.replace('.','_')
      8         sfile = zipfile.ZipFile(curr_dir+'/'+modname+'.jmu','r')

/home/docker/installed/JModelica/Python/pymodelica/compiler.py in compile_fmux(class_name, file_name, compiler, compiler_options, compile_to, compiler_log_level, separate_process, jvm_args)
    211     return _compile_unit(class_name, file_name, compiler, 'fmux', None, 'auto',
    212                 compiler_options, compile_to, compiler_log_level,
--> 213                 separate_process, jvm_args)
    214 
    215 def _compile_unit(class_name, file_name, compiler, target, version,

/home/docker/installed/JModelica/Python/pymodelica/compiler.py in _compile_unit(class_name, file_name, compiler, target, version, platform, compiler_options, compile_to, compiler_log_level, separate_process, jvm_args)
    246     else:
    247         return compile_separate_process(class_name, file_name, compiler, target, version, platform, 
--> 248                                         compiler_options, compile_to, compiler_log_level, jvm_args)
    249 
    250 def compile_separate_process(class_name, file_name=[], compiler='auto', target='me', version='1.0', 

/home/docker/installed/JModelica/Python/pymodelica/compiler.py in compile_separate_process(class_name, file_name, compiler, target, version, platform, compiler_options, compile_to, compiler_log_level, jvm_args)
    360         process.wait();
    361     finally:
--> 362         return log.end();
    363 
    364 def _gen_compiler_options(compiler_options):

/home/docker/installed/JModelica/Python/pymodelica/compiler_logging.py in end(self)
    332             raise IllegalCompilerArgumentError(exception.message)
    333 
--> 334         raise JError("%s\n%s" % (exception.message, exception.stacktrace))
    335 
    336 class CompilationException():

JError: Unknown tag: XML_vendorAnnotations
java.lang.RuntimeException: Unknown tag: XML_vendorAnnotations
	at org.jmodelica.modelica.compiler.AbstractGenerator.getTag(Unknown Source)
	at org.jmodelica.modelica.compiler.AbstractGenerator.generate(Unknown Source)
	at org.jmodelica.modelica.compiler.GenericXMLGenerator.generate(Unknown Source)
	at org.jmodelica.modelica.compiler.AbstractGenerator.generate(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.generateFile(Unknown Source)
	at org.jmodelica.modelica.compiler.Templates.generateXMLFiles(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.doGenerateCode(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.generateCode(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.doCompileModel(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.compileModel(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.doCompileUnit(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.compileUnit(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.compileUnit(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.compileModelFromCommandLine(Unknown Source)
	at org.jmodelica.modelica.compiler.ModelicaCompiler.main(Unknown Source)
```

**Comment by vruge** [comment]
I guess it would be nice to create a ticket for JModelica.org with fmux.

Other options are:
```python
from pyjmi import transfer_model
mx_model = transfer_model(name, curr_dir+"/thermodynamics_example.mo")
```
or you can try the xml output from OpenModelica
see.:
https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/optimization.html?highlight=optimization%20casadi

**Comment by yfuerst** [comment]
This actually works and I get the output
```
------------------------------- Variables -------------------------------

Time variable: time
parameter Modelica.SIunits.SpecificHeatCapacity R(bindingExpression = 287) = 287 /* 287 */;
Modelica.SIunits.Pressure P;
constant Modelica.SIunits.Volume V(bindingExpression = 0.001) = 0.001 /* 0.001 */;
Real der(m);
Modelica.SIunits.Mass m(start = 0.00119);
constant Modelica.SIunits.ThermodynamicTemperature T(bindingExpression = 293) = 293 /* 293 */;
constant Modelica.SIunits.MassFlowRate mdot_in(bindingExpression = 0.0001) = 0.0001 /* 0.0001 */;
constant Modelica.SIunits.MassFlowRate mdot_out(bindingExpression = 1e-05) = 1e-05 /* 1e-05 */;

---------------------------- Variable types  ----------------------------

Modelica.SIunits.Mass type = Real (min = 0, quantity = Mass, unit = kg);
Modelica.SIunits.MassFlowRate type = Real (quantity = MassFlowRate, unit = kg/s);
Modelica.SIunits.Pressure type = Real (displayUnit = bar, quantity = Pressure, unit = Pa);
Modelica.SIunits.SpecificHeatCapacity type = Real (quantity = SpecificHeatCapacity, unit = J/(kg.K));
Modelica.SIunits.ThermodynamicTemperature type = Real (displayUnit = degC, min = 0, nominal = 300, quantity = ThermodynamicTemperature, start = 288.15, unit = K);
Modelica.SIunits.Volume type = Real (quantity = Volume, unit = m3);
Real type (displayUnit = , fixed = 0, max = inf, min = -inf, nominal = 1, quantity = , start = 0, unit = );

------------------------------- Functions -------------------------------


------------------------------- Equations -------------------------------

 -- Initial equations -- 
m = 0.00119
 -- DAE equations -- 
der(m) = 9e-05
(0.001*P) = (293*(m*R))
```
How do I get this expression into CasADi? Is there a special function or class to call?

Thank you very much so far.

**Comment by vruge** [comment]
`mx_model` is an object  

you can try e.g.
```python
mx_model.getDaeResidual()
mx_model.getDaeEquations()
```
But I don't know if there is a  smart function.
Note: If you prefer to use transfer_model you will use casadi 2.1 without funny stuffs like code export.

**Comment by yfuerst** [comment]
You mean I am restricted to CasADi 2.1 because JModelica uses this version? I will definitely look into the OpenModelica solution, as I am very interested in using the `DaeBuilder` object.

**Comment by vruge** [comment]
https://github.com/casadi/casadi/issues/1882 :(

**Comment by jgillis** [comment]
Please bring the discussion to our forum if still unresolved.
