### ISSUE TITLE
Program can't create a solver with 'nlpsol' function

### ISSUE THREAD

**Issue by Nib1er** [casadi/casadi#2272]
Hello. I faced a specific problem with my project. There are two points in  the program with 'nlpsol' function. 
First point:
```python
D = MX.sym('D',3*len(t))

J = 0 
Y = []
lbg = []
lbx = []
ubg=[]
ubx = []
ig = []
for i in t:
    Ik = I(x0 = X, p = vertcat(D[i], D[i + len(t)], D[i+2*len(t)]))
    X = Ik['xf']
    Y += [X, D[i]+D[i + len(t)]+D[i+2*len(t)]]
    lbg += [0., 0.5, 1., 0.]
    ubg += [10., 10., 10., 30.]
    lbx += [0.0, 0.0, 0.0]
    ubx += [30.0, 30.0, 30.0]
    ig += [scn['Ds'], scn['Df'], scn['Dm']]

    J += scn['qb']*(X[0]-scn['bstat'])**2+\
         scn['qs']*(X[1]-scn['sstat'])**2+\
         scn['qf']*(X[2]-scn['fstat'])**2+\
         scn['r']*((D[i]+D[i+len(t)]+D[i+2*len(t)])-scn['D_set'])**2

nlp1 = {'x':D, 'f':J, 'g':vertcat(*Y)}
opts1 = {"ipopt.linear_solver":"mumps", 'ipopt.max_iter':100}
solver1 = nlpsol("solver1", "ipopt", nlp1, opts1)
```
Second point:
```python
P = MX.sym('P',4)

Jp = 0 
Yp = []
lbgp = []
ubgp=[]

Xp = xin
while flag2 == 0:
    Par = [] 
    Par0 = [scn['ks'],scn['kf'],scn['Ki'],scn['Ytot']]
    Xb = [] 
    Xs = []
    Xf = []
    flag2 = 1
#pdb.set_trace()
for i in range(k):
    Ik = I(x0 = Xp, p = vertcat(Ds[k-1],Df[k-1],Dm[k-1],P[0],P[1],P[2],P[3]))
    Xp = Ik['xf']
    Yp += [X]
    lbgp += [0., 0.5, 1]
    ubgp += [10., 10., 10.]
    if (Smes[k] == 0) and (Fmes[k] == 0):
        Jp += (X[0]-Bmes[k])**2
    else:
        Jp += (X[0]-Bmes[k])**2+\
        (X[1]-Smes[k])**2+\
        (X[2]-Fmes[k])**2
        
if k%3 == 0:
    nlp2 = {'x':P, 'f':Jp*0.5, 'g':vertcat(*Yp)}
    opts2 = {"ipopt.linear_solver":"mumps", 'ipopt.max_iter':100}
    solver2 = nlpsol("solver2", "ipopt", nlp2, opts2)
```
When I tried to run the program I got this error message:
```
Traceback (most recent call last):
  File "C:\Users\HP-Laptop\Desktop\Program.py", line 371, in <module>
    solver2 = nlpsol("solver2", "ipopt", nlp2, opts2)
  File "C:\Python27\lib\site-packages\casadi\casadi.py", line 15084, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/nlpsol.cpp:120: Cannot create 'solver2' since [D] are free.
```
How can I solve it and what is 'free' means in this case?

**Comment by jaeandersson** [comment]
Clean up your code. Looks like you are accidentally using expressions depending on "D" in the second snippet. For other questions like this: Please use the forum.
