### ISSUE TITLE
Resolve diagcat issue

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2284]
https://groups.google.com/forum/#!topic/casadi-users/56qNv_JaLHw

https://github.com/casadi/casadi/commit/f427f24b90e8ce78bdb8dbef008b63410d2f2910

**Comment by jaeandersson** [comment]
The implementation should have used recursive calls. It's more maintainable.

**Comment by jaeandersson** [comment]
Something like:
```c++
  MX MX::diagcat(const vector<MX>& x) {
    // Quick return if empty or single element
    if (x.empty()) return MX();
    if (x.size()==1) return x.front();
    // Call recursively if any 0-by-0 matrices
    if (has_empty(x, true)) return diagcat(trim_empty(x, true));
    // Create diagcat node
    return x.front()->get_diagcat(x);
 }
```

**Comment by jgillis** [comment]
More from forum:

```
>>> horzcat(SX([]), SX([1,2]))
SX(
[[00, 1],
 [00, 2]])
>>> horzcat(MX([]), MX([1,2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/.local/lib/python2.7/site-packages/casadi/casadi.py", line 467, in horzcat
    def horzcat(*args): return _horzcat(args)
  File "/home/marco/.local/lib/python2.7/site-packages/casadi/casadi.py", line 18924, in _horzcat
    return _casadi._horzcat(*args)
RuntimeError: .../casadi/core/mx.cpp:932: Assertion "ne[i].size1()==ne[0].size1()" failed:
horzcat dimension mismatch  x[1]:2x1 and x[0]: 0x1.
>>> horzcat(DM([]), DM([1,2]))
DM(
[[00, 1],
 [00, 2]])
>>> horzcat(DM([]), IM([1,2]))
IM(
[[00, 1],
``

**Comment by jgillis** [comment]
Still an issue for 3.6
