### ISSUE TITLE
Callback with Jacobian

### ISSUE THREAD

**Issue by alphaville** [casadi/casadi#2490]
This is a request for an example, which I believe would be nice to have on the website of CasADi.

I would like to have an example implementation of a Callback with a user-defined Jacobian. I tried to implement a callback for the quadratic function `f(x) = 0.5*x^2`, with `x \in R` (scalar) as follows

```python
class MyCallback(cs.Callback):

    def __init__(self, name, d, opts={}):
        cs.Callback.__init__(self)
        self.construct(name, opts)

    def get_n_in(self): return 1

    def get_n_out(self): return 1

    def init(self):
        pass

    def eval(self, arg):
        x = arg[0]
        f = 0.5 * x**2
        return [f]

    def has_jacobian(self, *_args):
        return True

    def get_jacobian(self, *args):
        x = cs.MX.sym('x', 1, 1)
        jf = cs.Function('jacf', [x], [x])
        return jf
```

but I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/chung/NetBeansProjects/RUST/optimization-engine/open-codegen/opengen/main.py", line 10, in <module>
    jf = f.jacobian()
  File "/home/chung/NetBeansProjects/RUST/optimization-engine/open-codegen/venv36/lib/python3.6/site-packages/casadi-3.4.5-py3.6-linux-x86_64.egg/casadi/casadi.py", line 12621, in jacobian
    return _casadi.Function_jacobian(self, *args)
RuntimeError: Error in Function::jacobian for 'f' [CallbackInternal] at .../casadi/core/function.cpp:811:
.../casadi/core/callback_internal.cpp:117: Error calling "get_jacobian" for object f:
SWIG director type mismatch in output value of type 'casadi::Function'
```

It seems that CasADi expects that the Jacobian takes two input arguments.

**Comment by JasonZhou404** [comment]
Any updates on this?

**Comment by jaeandersson** [comment]
> It seems that CasADi expects that the Jacobian takes two input arguments

Yes, a Jacobian function takes the non-differentiated output as an input. If it's not needed, it can be an all-zero sparse matrix:
```python
    def get_jacobian(self, *args):
        x = cs.MX.sym('x', 1, 1)
        f = cs.MX(1, 1)
        jf = cs.Function('jacf', [x, f], [x])
        return jf
```
I don't know if that solves your problem. Differentiable Callback functions never got quite mature.
