### ISSUE TITLE
Casadi is unable to find ipopt when compiling using pyinstaller

### ISSUE THREAD

**Issue by Ruud-K** [casadi/casadi#2526]
My code that uses Casadi runs without errors in Python (Python 3.7.4 [MSC v.1916 64 bit (AMD64)] on win32). However, when I compile my code to an executable using PyInstaller, Casadi can no longer locate ipopt. First, I thought this was related to the HSL license that was mentioned in an [older](https://github.com/casadi/casadi/issues/1932) issue. However, I use mumps as linear solver so that shouldn't be a problem.

I tried adding the ipopt binaries (casadi\libcasadi_nlpsol_ipopt.dll) to the executable, but that doesn't solve it:
```CasADi -  WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_nlpsol_ipopt.dll':
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried 'C:\Users\****\AppData\Local\Temp\_MEI206282\casadi' :
    Error code (WIN32): 126
  Tried '' :
    Error code (WIN32): 126
  Tried '.' :
    Error code (WIN32): 126") [.../casadi/core/plugin_interface.hpp:171]
2019-12-04 09:00:31,360 ERROR .../casadi/core/plugin_interface.hpp:417: Plugin 'ipopt' is not found.
Traceback (most recent call last):
  File "lib\site-packages\casadi\casadi.py", line 16673, in nlpsol
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'ipopt' is not found.
[15696] Failed to execute script run_file
```

I also tried adding the complete Casadi package to the path, but then I get the error:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\***\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\***\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "casadi.py", line 420, in <module>
Exception:
            CasADi is not running from its package context.

            You probably specified the wrong casadi directory.

            When setting PYTHONPATH or sys.path.append,
            take care not to add a trailing '/casadi'.


[21048] Failed to execute script closed_loop
```

What is stopping Casadi from working properly from inside the executable?

**Comment by jgillis** [comment]
Hi! I'm not familiar with pyinstaller.. Can you give a minimal example?

**Comment by Ruud-K** [comment]
An easy example is the [basic example](https://rtc-tools.readthedocs.io/en/stable/examples/optimization/basic.html) from the RTC tools package, that uses Casadi to calculate an optimal control input:

```
from rtctools.optimization.collocated_integrated_optimization_problem \
    import CollocatedIntegratedOptimizationProblem
from rtctools.optimization.csv_mixin import CSVMixin
from rtctools.optimization.modelica_mixin import ModelicaMixin
from rtctools.util import run_optimization_problem


class Example(CSVMixin, ModelicaMixin, CollocatedIntegratedOptimizationProblem):
    """
    A basic example for introducing users to RTC-Tools 2
    """

    def objective(self, ensemble_member):
        # Minimize water pumped. The total water pumped is the integral of the
        # water pumped from the starting time until the stoping time. In
        # practice, self.integral() is a summation of all the discrete states.
        return self.integral('Q_release', ensemble_member)

    def path_constraints(self, ensemble_member):
        # Call super() class to not overwrite default behaviour
        constraints = super().path_constraints(ensemble_member)
        # Constrain the volume of storage between 380000 and 420000 m^3
        constraints.append((self.state('storage.V'), 380000, 420000))
        return constraints


if __name__ == '__main__':
    from datetime import datetime

    import matplotlib.dates as mdates
    import matplotlib.pyplot as plt

    import numpy as np

    # Run
    run_optimization_problem(Example, base_folder='yourlocation\minimal_example')

    # Import Data
    output_data_path = "../output/timeseries_export.csv"
    results = np.recfromcsv(output_data_path, encoding=None)
    input_data_path = "../input/timeseries_import.csv"
    input_data = np.recfromcsv(input_data_path, encoding=None)

    # Get times as datetime objects
    times = list(map(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"), results["time"]))

    # Generate Plot
    n_subplots = 2
    fig, axarr = plt.subplots(n_subplots, sharex=True, figsize=(8, 3 * n_subplots))
    axarr[0].set_title("Water Volume and Discharge")

    # Upper subplot
    axarr[0].set_ylabel("Water Volume [mÂ³]")
    axarr[0].ticklabel_format(style="sci", axis="y", scilimits=(0, 0))
    axarr[0].plot(times, results["v_storage"], label="Storage", linewidth=2, color="b")
    axarr[0].plot(
        times,
        [420000] * len(times),
        label="Storage Max",
        linewidth=2,
        color="r",
        linestyle="--",
    )
    axarr[0].plot(
        times,
        [380000] * len(times),
        label="Storage Min",
        linewidth=2,
        color="g",
        linestyle="--",
    )

    # Lower Subplot
    axarr[1].set_ylabel("Flow Rate [mÂ³/s]")
    axarr[1].plot(times, input_data["q_in"], label="Inflow", linewidth=2, color="g")
    axarr[1].plot(times, results["q_release"], label="Release", linewidth=2, color="r")

    # Format bottom axis label
    axarr[-1].xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))

    # Shrink margins
    fig.tight_layout()

    # Shrink each axis and put a legend to the right of the axis
    for i in range(n_subplots):
        box = axarr[i].get_position()
        axarr[i].set_position([box.x0, box.y0, box.width * 0.8, box.height])
        axarr[i].legend(loc="center left", bbox_to_anchor=(1, 0.5), frameon=False)

    plt.autoscale(enable=True, axis="x", tight=True)

    # Output Plot
    plt.show()
```
Make sure to adhere to the folder structure mentioned in the link and download the Modelica model. Also you will need to specify the base_folder of the model/input/output folders when executing the problem! Then the required packages are:
```
altgraph==0.16.1
antlr4-python3-runtime==4.7.2
casadi==3.5.1
cycler==0.10.0
future==0.18.2
kiwisolver==1.1.0
matplotlib==3.1.2
numpy==1.17.4
pefile==2019.4.18
PyInstaller==3.5
pymoca==0.6.2
pyparsing==2.4.5
python-dateutil==2.8.1
pywin32-ctypes==0.2.0
rtc-tools==2.4.0a6
rtc-tools-channel-flow==1.1.0
rtc-tools-hydraulic-structures==2.0.0a8
scipy==1.3.3
six==1.13.0
```
And you can run PyInstaller over example.py: `pyinstaller example.py`

Then, simply cd to the executable location using command prompt and execute it.

**Comment by Ruud-K** [comment]
I solved this issue by using a [Depency checker](https://github.com/lucasg/Dependencies/) on the ipopt binaries (casadi\libcasadi_nlpsol_ipopt.dll). It turns out the following DLL-filed are needed to run Casadi with an executable (with just mumps):
- libcasadi.dll
   - libcasadi_nlpsol_ipopt.dll
      - libgfortran-3.dll
         - libquadmath-0.dll

These can be added to the Pyinstaller specification file:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

dlls =     [('\\casadi\\libcasadi.dll', '.'), 
 ('casadi\\libcasadi_nlpsol_ipopt.dll', '.'), 
('\casadi\\libgfortran-3.dll', '.'), 
('\\casadi\\libquadmath-0.dll', '.')]
				
a = Analysis(['script_name.py'],
             pathex=['path_to_script'],
             binaries=dlls,
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='script_name',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='script_name')
```

I only got this to work in a distribution where the binaries are located outside the executable. For a standalone single executable file I couldn't get it to work, likely due to the binaries not being located in the correct internal path/location.

**Comment by toshiharutf** [comment]
I had a similar issue on Linux Ubuntu 20.04. casadi==3.5.5, pyinstaller==5.1
I got this error: 

`...
  Tried '' :
    Error code: libgfortran-ed201abd.so.3.0.0: cannot open shared object file: No such file or directory
...
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'ipopt' is not found.
`



After checking the /dist output folder, I found that the libgfortran library was a different version of the one described on the error

I fixed using a custom spec file:

`
block_cipher = None

libs = [('libgfortran-ed201abd.so.3.0.0', '.'),
('libcasadi_nlpsol_ipopt.so', '.')]

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=libs,
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='app',
)
`
