### ISSUE TITLE
Non informative error in Callback eval method

### ISSUE THREAD

**Issue by preisleistung** [casadi/casadi#2610]
I am creating a callback class for integrating Pytorch in casadi.
I noticed that the following core:

```        
net = Net(n_feature=2, n_hidden=10, n_output=1)

        class NetCallback(ca.Callback):
            def __init__(self, name, net, opts={}):
                ca.Callback.__init__(self)
                self.net = net
                self.construct(name, opts)

            def get_n_in(self): return 1

            def get_n_out(self): return 1

            def get_sparsity_in(self, i):
                return ca.Sparsity.dense(self.net.n_feature, 1)

            def get_sparsity_out(self, i):
                return ca.Sparsity.dense(self.net.n_output, 1)

            def eval(self, arg):
                arg0 = torch.tensor(np.array(arg[0]).T, device=self.net.device, dtype=self.net.dtype)
                return ca.DM(self.net(arg0).detach().numpy())
```

returns an error 

```
Traceback (most recent call last):
  File "C:\Users\Bruno\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Bruno\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\Bruno\OneDrive\Work\BioEng\projects\machine_learning\IMPRS2020\tests\test_casadi_pytorch_callback.py", line 34, in test_simple_callback
    print(casadi_net(np.array([3, 2])))
  File "C:\Users\Bruno\Documents\python_packages\learning_baker_hughes\lib\site-packages\casadi\casadi.py", line 13334, in __call__
    ret = self.call(args)
  File "C:\Users\Bruno\Documents\python_packages\learning_baker_hughes\lib\site-packages\casadi\casadi.py", line 12214, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.cpp:3344: Failed to evaluate 'eval_dm' for test:
.../casadi/core/callback_internal.cpp:109: Error calling "eval" for object test:
SWIG director type mismatch in output value of type 'std::vector< casadi::DM,std::allocator< casadi::DM > >'
```

the problem is that the return of `def eval(self,arg)` does not return a list. If I write

```
            def eval(self, arg):
                arg0 = torch.tensor(np.array(arg[0]).T, device=self.net.device, dtype=self.net.dtype)
                return [ca.DM(self.net(arg0).detach().numpy())]
```
everything works. Maybe it would be good to check the type of the return element and give a more informative error?

**Comment by kkxchen** [comment]
Hi,  I have a similar problem. What if the output dimension is not 1 but N*1?

**Comment by seanjkanderson** [comment]
I'm trying to run the gpflow_example.py [script](https://web.casadi.org/blog/tensorflow/gpflow_example.py) from the casadi website. Some of the behavior in that script is outdated.

My updated example is the following:
```
from casadi import *
from pylab import *
import tensorflow as tf
import gpflow

# Needs: pip install gpflow casadi

# Create data points: a noisy sine wave
N = 20
np.random.seed(0)
data = np.linspace(0, 10, N).reshape((N, 1))
value = np.sin(data) + np.random.normal(0, 0.1, (N, 1))

# Perform Gaussian process regression
model = gpflow.models.GPR((data, value), gpflow.kernels.Constant(1) + gpflow.kernels.Linear(1) + gpflow.kernels.White(
    1) + gpflow.kernels.RBF(1))
opt = gpflow.optimizers.Scipy()
opt.minimize(model.training_loss, model.trainable_variables, options=dict(maxiter=100))


# Package the resulting regression model in a CasADi callback
class GPR(Callback):
    def __init__(self, name, opts: dict = None):
        if opts is None:
            opts = dict()

        Callback.__init__(self)
        self.construct(name, opts)

    def eval(self, arg):
        [mean, _] = model.predict_f(np.array(arg[0]))
        return [mean]


# Instantiate the Callback (make sure to keep a reference to it!)
gpr = GPR('GPR', opts={"enable_fd": True})
print(gpr)

# Find the minimum of the regression model
x = MX.sym("x")
solver = nlpsol("solver", "ipopt", {"x": x, "f": gpr(x)})
res = solver(x0=5)

plot(res["x"], gpr(res["x"]), 'k*', markersize=10, label="Function minimum by CasADi/Ipopt")
legend()
savefig('gpflow1d_min.png', bbox_inches='tight')
```
However, my traceback indicates a Runtime Error associated with the callback function.
```
2022-02-11 15:24:16.043401: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:AutoGraph could not transform <function Scipy.eval_func.<locals>._tf_eval at 0x7fcbb06d7ef0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
GPR:(i0)->(o0) CallbackInternal

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.3, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        1

CasADi - 2022-02-11 15:24:17 WARNING("solver:nlp_grad_f failed:Error in Function::operator() for 'nlp_grad_f' [MXFunction] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'GPR' [CallbackInternal] at .../casadi/core/function.cpp:1368:
.../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for GPR:
.../casadi/core/callback_internal.cpp:122: Error calling "eval" for object GPR:
SWIG director type mismatch in output value of type 'std::vector< casadi::DM,std::allocator< casadi::DM > >'") [.../casadi/core/oracle_function.cpp:223]
Error evaluating objective gradient at user provided starting point.
  No scaling factor for objective function computed!
Total number of variables............................:        1
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

CasADi - 2022-02-11 15:24:17 WARNING("solver:nlp_grad_f failed:Error in Function::operator() for 'nlp_grad_f' [MXFunction] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'GPR' [CallbackInternal] at .../casadi/core/function.cpp:1368:
.../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for GPR:
.../casadi/core/callback_internal.cpp:122: Error calling "eval" for object GPR:
SWIG director type mismatch in output value of type 'std::vector< casadi::DM,std::allocator< casadi::DM > >'") [.../casadi/core/oracle_function.cpp:223]

Number of Iterations....: 0

Number of objective function evaluations             = 0
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.052
Total CPU secs in NLP function evaluations           =      0.041

EXIT: Invalid number in NLP function or derivative detected.
      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
  nlp_grad_f  |  95.09ms ( 47.55ms) 102.24ms ( 51.12ms)         2
       total  |  96.08ms ( 96.08ms) 103.22ms (103.22ms)         1
Traceback (most recent call last):
  File "/Users/seananderson/Documents/research/NMPC_GP/batch_opt/gpflow_example.py", line 60, in <module>
    plot(res["x"], gpr(res["x"]), 'k*', markersize=10, label="Function minimum by CasADi/Ipopt")
  File "/Users/seananderson/anaconda3/envs/ml/lib/python3.7/site-packages/casadi/casadi.py", line 8497, in __call__
    ret = self.call(args)
  File "/Users/seananderson/anaconda3/envs/ml/lib/python3.7/site-packages/casadi/casadi.py", line 7679, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for GPR:
.../casadi/core/callback_internal.cpp:122: Error calling "eval" for object GPR:
SWIG director type mismatch in output value of type 'std::vector< casadi::DM,std::allocator< casadi::DM > >'
```
I'm just getting started with callback functions and tensorflow with casadi, so I'm assuming I'm doing something wrong here. The output from eval is a list, so it's not clear to what is going wrong.
 Thank you!

**Comment by JIEZHUZED** [comment]
@seanjkanderson 
I have the same problem.
But,  when I print [mean], it  return a tf.tensor.
You need to add .numpy() to the return value

For example:
def eval(self, arg):
        [mean, _] = model.predict_f(np.array(arg[0]))
        **return [mean.numpy()]**
I tried running it and it seemed to work.
