### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MazenMazou** [casadi/casadi#2617]
Hello
I successfully installed casadi on my mac by doing it manually (pip could not find it!)
I am facing the same problem now on windows 10 except that manual installation is not working (downloading the 64bit version and putting the files in the site-packages path).

This is what pip3 install casadi returns:
ERROR: Could not find a version that satisfies the requirement casadi (from versions: none)
ERROR: No matching distribution found for casadi

This is what import casadi returns:

C:\Users\Mazen>python3
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import casadi
Traceback (most recent call last):
  File "C:\Users\Mazen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\casadi\casadi.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _casadi: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mazen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\casadi\__init__.py", line 32, in <module>
    from casadi.casadi import *
  File "C:\Users\Mazen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\casadi\casadi.py", line 21, in <module>
    _casadi = swig_import_helper()
  File "C:\Users\Mazen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\casadi\casadi.py", line 20, in swig_import_helper
    return importlib.import_module('_casadi')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_casadi'

Thanks in advance for your help,
Cheers !

**Comment by jgillis** [comment]
Python 3.8 support only for Linux at this point, sorry..

**Comment by MazenMazou** [comment]
I downgraded mine to 3.7.7 and the installation works perfectly !
Thank you
