### ISSUE TITLE
Reverse-mode differentiation on SUNDIALS integrators fails with non-trivial 'grid' options or 'output_t0'

### ISSUE THREAD

**Issue by mirhahn** [casadi/casadi#2619]
This problem can be reproduced by running the following code on an up-to-date working copy of the 'develop' branch (commit 059ef9eb873f3cf46dfa75bd8b40d60e47189799), though it may work with the 'master' branch as well.

```python
from casadi import *

x = MX.sym('x')
p = MX.sym('p')

dae = {
        'x': x,
        'p': p,
        'ode': x * p,
        'quad': (x - 1)**2,
        }
daesol = integrator(
        'daesol',
        'cvodes',
        dae,
        {
            'grid': numpy.linspace(0, 10, 101),
            'output_t0': True
        })

out = daesol(x0=5, p=p)
grad = gradient(out['qf'][:,-1], p)
```
For me, this produces the following output:
```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    grad = gradient(out['qf'][:,-1], p)
  File "/home/mhahn/.local/lib/python3.8/site-packages/casadi/casadi.py", line 21687, in gradient
    return _casadi.gradient(*args)
RuntimeError: Error in MX::gradient at .../casadi/core/generic_matrix.hpp:1203:
Error in MX::jtimes at .../casadi/core/generic_matrix.hpp:1191:
Error in MX::reverse at .../casadi/core/mx.cpp:1741:
Error in MXFunction::ad_reverse at .../casadi/core/mx_function.cpp:1042:
Error in MX::ad_reverse for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2039:
Error in Call::ad_reverse for 'daesol' [CvodesInterface] at .../casadi/core/casadi_call.cpp:147:
Error in Function::reverse for 'daesol' [CvodesInterface] at .../casadi/core/function.cpp:1025:
.../casadi/core/function.cpp:1613: Assertion "size1_in(i)==nrow && size2_in(i)==ncol" failed:
Incorrect shape for adj1_daesol:(x0,p,z0[0],rx0[0],rp[0],rz0[0],out_xf[1x1,0nz],out_qf[1x1,0nz],out_zf[0],out_rxf[0],out_rqf[0],out_rzf[0],adj_xf,adj_qf,adj_zf[0],adj_rxf[0],adj_rqf[0],adj_rzf[0])->(adj_x0,adj_p,adj_z0[0],adj_rx0[0],adj_rp[0],adj_rz0[0]) MXFunction input 3 "rx0". Expected 0-by-101 but got 0-by-1
```
This may have something to do with the liberal use of `vec` calls in `Integrator::aug_adj`, which would shorten a 0-by-101 vector to 0-by-1. If this is the case `aug_adj` would not be appropriate for the function signature of an integrator with a non-trivial `grid` and this should occur for all integrators. I have so far only tested this behaviour in IDAS and CVODES.

The desired result (single integration, differentiable output at multiple intermediate times) can be approximated using map-accumulated integrator calls, though the result has inferior performance for fine time grids.

Both `grid` and `output_t0` can produce the effect independently, though the dimension of `rx0` will of course be different.

**Comment by jgillis** [comment]
This is a known not-so-low-hanging fruit since #1592,
but let's keep this more specific issue to address it.
