### ISSUE TITLE
RuntimeError: Cannot create 'solver' since parameters are free.

### ISSUE THREAD

**Issue by KuangHaofei** [casadi/casadi#2680]
Hi,

I meet the strange running error:

```
terminate called after throwing an instance of 'casadi::CasadiException'
  what():  .../casadi/core/nlpsol.cpp:120: Cannot create 'OED' since [u_abstract_1, u_abstract_0] are free.
``` 

And I find a closed issue about it: #2086 

The error is fixed at this issue. But while I try the python code, I also meet the error.

code:
```python
from casadi import *

x = MX.sym("x")
p = MX.sym("p")

# We should either make this line fail with a friendly error,
solver = nlpsol("solver", "ipopt", {"x": x, "f": (x - p) ** 2}, dict(verbose=True))

ret = solver(x0=x)

f = Function('solver', [x, p], [ret["x"]])

# or make this output '2', and make `solver(x0=0)` fail
print(f(2, 2))
```

error:
```
Traceback (most recent call last):
  File "/Users/kuanghaofei/Desktop/casadi_test/casadi_test.py", line 7, in <module>
    solver = nlpsol("solver", "ipopt", {"x": x, "f": (x - p) ** 2}, dict(verbose=True))
  File "/Users/kuanghaofei/opt/anaconda3/envs/casadi_test/lib/python3.8/site-packages/casadi/casadi.py", line 16847, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/nlpsol.cpp:120: Cannot create 'solver' since [p] are free.
```

python env:
```
conda create --name casadi_test python=3.8
conda activate casadi_test
conda install numpy
pip install casadi
```

Any suggestion? THX!

**Comment by tmmsartor** [comment]
I am not sure what you want to do, but if you want to pass 'p' as parameter 
you have to tell `nlpsol` to expect a parameter.

```
from casadi import *

x = MX.sym("x")
p = MX.sym("p")

# We should either make this line fail with a friendly error,
solver = nlpsol("solver", "ipopt", {"x": x, "p":p, "f": (x - p) ** 2}, dict(verbose=True))

pi = MX.sym("pi")
x0 = MX.sym("x0")
# NB: you can also reuse the same symbol of before
ret = solver(x0=x0, p=pi)

f = Function('solver', [x0, pi], [ret["x"]])

# should print 2
print(f(2, 2))
```
Is this close to what you want to do?

See also `print(solver)` to have an idea of the arguments you can pass

NB: Keep in mind that for "usage" questions there is also the [forum](https://groups.google.com/forum/#!forum/casadi-users)

**Comment by KuangHaofei** [comment]
Hi， 

Thanks a lot. TBH, I am just trying to write C++ code to use Casadi for solving a nonlinear problem, but got this error. Then I found there is a similar error in this Python code. Anyway your comment already solves the Python Error. Thanks again

Btw, do you have any reference for Casadi C++ programing?

THX!
