### ISSUE TITLE
Linker problem with `conic` (Mac/Python/Anaconda)

### ISSUE THREAD

**Issue by apotschka** [casadi/casadi#2722]
Hi Joel and Joris!

I am using CasADi in my current Nonlinear Optimization course at TU Clausthal with great success. Thanks for all your efforts!

There seems to be a linkage issue when using the Python interface to `conic` on OSX (BigSur, but probably also earlier),  Anaconda (v4.9.2) distribution. The [minimum working example](https://gist.github.com/apotschka/9013d9ed1c5ff67d1587025bf78f7697) generates the following output:

```
(casadi) potschka@andreass-mbp casadi % python conic_mac.py
CasADi - 2021-01-22 11:15:38 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_qpoases.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/opt/anaconda3/envs/casadi/lib/python3.8/site-packages/casadi' :
    Error code: dlopen(/opt/anaconda3/envs/casadi/lib/python3.8/site-packages/casadi/libcasadi_conic_qpoases.dylib, 5): Symbol not found: _mkl_blas_caxpy
  Referenced from: /opt/anaconda3/envs/casadi/lib/libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /opt/anaconda3/envs/casadi/lib/libmk... truncated") [.../casadi/core/plugin_interface.hpp:171]
Traceback (most recent call last):
  File "conic_mac.py", line 5, in <module>
    S = conic("S", "qpoases", {"h": H.sparsity(), "a": A.sparsity()})
  File "/opt/anaconda3/envs/casadi/lib/python3.8/site-packages/casadi/casadi.py", line 15637, in conic
    return _casadi.conic(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'qpoases' is not found.
```

I can make it run by preloading some required MKL required libraries:

```
(casadi) potschka@andreass-mbp casadi % DYLD_INSERT_LIBRARIES=/opt/anaconda3/envs/casadi/lib/libmkl_mc.dylib:/opt/anaconda3/envs/casadi/lib/libmkl_core.dylib:/opt/anaconda3/envs/casadi/lib/libmkl_sequential.dylib python conic_mac.py


####################   qpOASES  --  QP NO.   1   #####################

    Iter   |    StepLength    |       Info       |   nFX   |   nAC    
 ----------+------------------+------------------+---------+--------- 
       0   |   1.866666e-07   |   ADD CON    0   |     1   |     1   
       1   |   1.333333e-08   |   REM BND    1   |     0   |     1   
       2   |   1.000000e+00   |    QP SOLVED     |     0   |     1   
```

I guess some dependencies for dynamic linking have to be added.

My TA tells me it's working on Windows with Anaconda.

Best wishes,
Andreas

**Comment by jgillis** [comment]
Thank you, Andreas!

We are aware of this regression issue on Mac. I'm probably going to switch our binaries to openblas for future releases which we can distribute along with the binaries.

**Comment by andiRitter** [comment]
Hi there, sorry for posting to an already closed issue. However, I'm having the same issues with superscs and would really like to use it.

I tried the same approach than described above using Matlab (9.8.0.1451342 (R2020a) Update 5) on macOS Mojave (Version10.14.6) using

```
DYLD_INSERT_LIBRARIES=/usr/local/lib/libmkl_mc3.dylib.dylib:/usr/local/lib/libmkl_core.dylib:/usr/local/lib/libmkl_sequential.dylib /Applications/MATLAB_R2020a.app/bin/matlab
```

after installing oneMKL from [software.intel.com](https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html)

and linking the libraries using

```
ln -s /opt/intel/lib/* /usr/local/lib
ln -s /opt/intel/mkl/lib/* /usr/local/lib
```

But I wasn't successful. I'm using the latest version 3.5.5 of Casadi and get the following error after calling (one of your examples)

```
import casadi.*
options = struct('eps', 1e-9, 'do_super_scs', 1, 'verbose', 0);
opti = Opti('conic');
x = opti.variable();
y = opti.variable();
h = soc(vertcat(x - 5, y - 7) ,4);
opti.subject_to(h > 0);
opti.minimize(2 * x + y);
opti.solver('superscs', struct(), options);
sol = opti.solve();
```

```
CasADi - 2021-03-05 15:16:40 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_superscs.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/Users/andi/Documents/MATLAB/casadi/casadi-osx-matlabR2015a-v3.5.5' :
    Error code: dlopen(/Users/andi/Documents/MATLAB/casadi/casadi-osx-matlabR2015a-v3.5.5/libcasadi_conic_superscs.dylib, 5): Symbol not found: _mkl_blas_caxpy
  Referenced from: /usr/local/lib/libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /usr/local/lib/libmkl_intel_lp64.dylib
  Tried '' :
    Error code: dlopen(libcasadi_conic_superscs.dylib, 5): Symbol not found: _mkl_blas_caxpy
  Referenced from: /usr/local/lib/libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /usr/local/lib/libmkl_intel_lp64.dylib
  Tried '.' :
    Error code: dlopen(./libcasadi_conic_superscs.dylib, 5): Symbol not found: _mkl_blas_caxpy
  Referenced from: /usr/local/lib/libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /usr/local/lib/libmkl_intel_lp64.dylib") [.../casadi/core/plugin_interface.hpp:171]
```

The symbols are indeed not in `libmkl_intel_lp64.dylib`, as the following indicates
```
nm /usr/local/lib/libmkl_intel_lp64.dylib | grep _mkl_blas_caxpy
                 U _mkl_blas_caxpy
                 U _mkl_blas_caxpy_batch
                 U _mkl_blas_caxpy_batch_strided
                 U _mkl_blas_caxpyi
```

but they are in `libmkl_sequential.dylib`:
```
nm /usr/local/lib/libmkl_sequential.dylib | grep _mkl_blas_caxpy
00000000000032d0 T _mkl_blas_caxpy
0000000000003310 T _mkl_blas_caxpy_batch
00000000000035a0 T _mkl_blas_caxpy_batch_strided
00000000000038a0 T _mkl_blas_caxpy_direct
000000000158efe0 T _mkl_blas_caxpyi
```

Do I understand it correctly, that the problem is caused by `libcasadi_conic_superscs.dylib` which is not loading `libmkl_sequential.dylib`, but should do so? Would it help to try to compile the entire MLK library into a single `libmkl_intel_lp64.dylib` file? Any suggestions how to do that? Thanks a lot for the amazing work you're doing! Andi

**Comment by aghezz1** [comment]
Hi Joris!

I came across this issue opened by Andreas because I can't run qpoases on MacOS 12.3.1. The error message is very similar to the ones of Andreas and Andi. Casadi failed to load ```libmkl_intel_lp64.dylib```.

Is there any solution to fix this problem definitely (e.g. custom build from source) or the only way is to add to the ```DYLD_LIBRARY_PATH``` all the required ```mkl``` libraries?

Just for completeness, by running [minimum working example](https://gist.github.com/apotschka/9013d9ed1c5ff67d1587025bf78f7697) I get this error message (I'm not using Anaconda but pyenv with virtualenv and pip as installer).
```CasADi - 2022-05-02 11:47:57 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_qpoases.dylib':
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/Users/aghezzi/.pyenv/versions/venv_racecars/lib/python3.8/site-packages/casadi' :
    Error code: dlopen(/Users/aghezzi/.pyenv/versions/venv_racecars/lib/python3.8/site-packages/casadi/libcasadi_conic_qpoases.dylib, 0x0005): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/aghezzi/.pyenv/versions/3.8.12/envs/venv_racecars/lib/python... truncated") [.../casadi/core/plugin_interface.hpp:171]
Traceback (most recent call last):
  File "min_example.py", line 6, in <module>
    S = conic("S", "qpoases", {"h": H.sparsity(), "a": A.sparsity()})
  File "/Users/aghezzi/.pyenv/versions/venv_racecars/lib/python3.8/site-packages/casadi/casadi.py", line 15637, in conic
    return _casadi.conic(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'qpoases' is not found.
```

Thank you for the support, I really appreciate it 😄 
Best,
Andrea
