### ISSUE TITLE
Casadi not working under Python 3.10

### ISSUE THREAD

**Issue by aaaandi** [casadi/casadi#2877]
Hi everyone, I just figured out that CasADi is not working on Python 3.10. I created a [dummy project on GitHub](https://github.com/aaaandi/test-casadi-python-3.10) to illustrate the issue:

- The [workflow with python3.9](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784664?check_suite_focus=true) passes.
- The [workflow with python3.10](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true) fails, see error below.

```
CasADi - 2022-02-08 13:26:49 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
[5](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:5)
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_nlpsol_ipopt.so': 
[6](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:6)
   (
[7](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:7)
    Searched directories: 1. casadipath from GlobalOptions
[8](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:8)
                          2. CASADIPATH env var
[9](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:9)
                          3. PATH env var (Windows)
[10](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:10)
                          4. LD_LIBRARY_PATH env var (Linux)
[11](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:11)
                          5. DYLD_LIBRARY_PATH env var (osx)
[12](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:12)
    A library may be 'not found' even if the file exists:
[13](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:13)
          * library is not compatible (different compiler/bitness)
[14](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:14)
          * the dependencies are not found
[15](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:15)
   )
[16](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:16)
  Tried '/usr/local/lib/python3.10/site-packages/casadi' :
[17](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:17)
    Error code: libgfortran.so.5: cannot open shared object file: No such file or directory
[18](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:18)
  Tried '' :
[19](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:19)
    Error code: libgfortran.so.5: cannot open shared object file: No such file or directory
[20](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:20)
  Tried '.' :
[21](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:21)
    Error code: ./libcasadi_nlpsol_ipopt.so: cannot open shared object file: No such file or directory") [.../casadi/core/plugin_interface.hpp:171]
[22](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:22)
Traceback (most recent call last):
[23](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:23)
  File "/__w/test-casadi-python-3.10/test-casadi-python-3.10/run_dummy_problem.py", line 30, in <module>
[24](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:24)
    solver = nlpsol('solver', 'ipopt', nlp)
[25](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:25)
  File "/usr/local/lib/python3.10/site-packages/casadi/casadi.py", line 16865, in nlpsol
[26](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:26)
    return _casadi.nlpsol(*args)
[27](https://github.com/aaaandi/test-casadi-python-3.10/runs/5109784697?check_suite_focus=true#step:7:27)
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'ipopt' is not found.
```

The example ist based on a code sample from https://web.casadi.org. Do you have any plans for releasing a new version that runs with python3.10?

**Comment by jgillis** [comment]
Release is underway..

**Comment by GijsGroote** [comment]
Any update so far?

**Comment by arthursn138** [comment]
Any updates?

**Comment by GuillermoGarciaF** [comment]
Hello, thank you for your efforts and for developing such a nice package.
Are there any updates on supporting Python 3.10?

Thank you
