### ISSUE TITLE
Assertion fail in `Function.generate`

### ISSUE THREAD

**Issue by harry7557558** [casadi/casadi#3006]
I'm trying to generate C code for a function and I'm getting the following error:

```
Traceback (most recent call last):
  File "d:\Coding\GitHub\adr_ws-2022\src\gcopter\dynamics\generate_f.py", line 77, in <module>
    xz.generate('dynamics/fxz.c')
  File "C:\Users\harry\AppData\Local\Programs\Python\Python39\lib\site-packages\casadi\casadi.py", line 12702, in generate
    return _casadi.Function_generate(self, *args)
RuntimeError: .../casadi/core/code_generator.cpp:143: Assertion "Function::check_name(this->name)" failed:
Notify the CasADi developers.
```

Code (not yet finished):

```py
from casadi import *

def N(x):
    return x / norm_2(x)

def DN(x):
    return (SX_eye(3) - x @ transpose(x) / dot(x, x)) / norm_2(x)

def quat2rot(q):
    s = 1 / dot(q, q)
    qr, qi, qj, qk = q[0], q[1], q[2], q[3]
    return vertcat(
        horzcat(
            1-2*s*(qj*qj+qk*qk),
            2*s*(qi*qj-qk*qr),
            2*s*(qi*qk+qj*qr)
        ),
        horzcat(
            2*s*(qi*qj+qk*qr),
            1-2*s*(qi*qi+qk*qk),
            2*s*(qj*qk-qi*qr)
        ),
        horzcat(
            2*s*(qi*qk-qj*qr),
            2*s*(qj*qk+qi*qr),
            1-2*s*(qi*qi+qj*qj)
        )
    )

# constants
m = SX.sym('m', 1)  # mass
g = SX.sym('g', 1)  # gravity
e3 = SX([0, 0, 1])
dh, dv = SX.sym('dh', 1), SX.sym('dv', 1)
D = diag(vertcat(dh, dh, dv))  # drag coefficient
sigma = lambda v: norm_2(v)  # time independent drag \propto v^2
M = SX.sym('M', 3, 3)  # moment of inertia

# z
r = SX.sym('r', 3)
phi = SX.sym('phi', 1)

# independent derivatives of z
v = SX.sym('v', 3)  # r'
a = SX.sym('a', 3)  # r"
j = SX.sym('j', 3)  # r"'
beta = SX.sym('beta', 1)  # phi'

# f
zb = N(a + dh/m*sigma(v)*v + g*e3)
f = dot(zb, m*a + dv*sigma(v)*v + m*g*e3)

# R
q = vertcat(
    (1+zb[2])*cos(phi/2),
    -zb[1]*cos(phi/2) + zb[0]*sin(phi/2),
    zb[0]*cos(phi/2)+zb[1]*sin(phi/2),
    (1+zb[2])*sin(phi/2)
) / sqrt(2*(1+zb[2]))
R = quat2rot(q)

# w
dzb = dh/m * transpose(DN(a+dh/m*sigma(v)*v+g*e3)) @ (m/dh*j+sigma(v)*a)
w = vertcat(
    dzb[0]*sin(phi)-dzb[1]*cos(phi)-dzb[2]*(zb[0]*sin(phi)-zb[1]*cos(phi))/(1+zb[2]),
    dzb[0]*cos(phi)+dzb[1]*sin(phi)-dzb[2]*(zb[0]*cos(phi)+zb[1]*sin(phi))/(1+zb[2]),
    (zb[1]*dzb[0]-zb[0]*dzb[1])/(1+zb[2]) + beta
)

z = vertcat(r, phi)
x = vertcat(r, v, reshape(R, (9, 1)), w)

# xz = Function('xz', [z], [x], ['z'], ['x'])
xz = Function('xz', [r, phi], [r, v, R, w], ['r', 'phi'], ['r', 'v', 'R', 'w'])
xz.generate('dynamics/fxz.c')
```

Python 3.9.1. Windows 64-bit. Casadi 3.5.5 installed via `pip`.

I'm a beginner to Casadi and I can't guarantee my code is correct and conventional. I wonder if there is a quick way to fix this issue on my end since my project deadline is approaching. Thanks in advance.

**Comment by harry7557558** [comment]
I got it working by changing `dynamics/fxz.c` to `fxz.c`. Thanks anyway!
