### ISSUE TITLE
Tiny mismatch in serialize roundtrip on Windows

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3040]
```
2023-03-21T21:02:12.3542219Z FAIL: test_MX (ad.ADtests)
2023-03-21T21:02:12.3542805Z ----------------------------------------------------------------------
2023-03-21T21:02:12.3543280Z Traceback (most recent call last):
2023-03-21T21:02:12.3543780Z   File "D:\a\casadi\casadi\test\python\ad.py", line 632, in test_MX
2023-03-21T21:02:12.3544300Z     self.check_codegen(fun,inputs=values,std=std)
2023-03-21T21:02:12.3544850Z   File "D:\a\casadi\casadi\test\python\helpers.py", line 700, in check_codegen
2023-03-21T21:02:12.3545384Z     self.checkarray(Fout[i],Fout2[i],digits=15)
2023-03-21T21:02:12.3546033Z   File "D:\a\casadi\casadi\test\python\helpers.py", line 311, in checkarray
2023-03-21T21:02:12.3547007Z     self.assertAlmostEqual(zt[i,j],zr[i,j],digits,LazyString('"In %s: %s evaluation error.\n %s <->\n %s\n [digits=%d] at elem(%d,%d): " % (name,failmessage,str(zt),str(zr), digits, i,j, )'))
2023-03-21T21:02:12.3547781Z   File "D:\a\casadi\casadi\test\python\helpers.py", line 264, in assertAlmostEqual
2023-03-21T21:02:12.3548465Z     unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
2023-03-21T21:02:12.3549467Z AssertionError: DM(22.2776) != DM(22.2776) within 15 places (3.552713678800501e-15 difference) : In :  evaluation error.
2023-03-21T21:02:12.3550044Z  [[00, 22.2776]] <->
2023-03-21T21:02:12.3550449Z  [[00, 22.2776]]
2023-03-21T21:02:12.3551007Z  [digits=15] at elem(0,1):  2.2277580000000004e+01 <-> 2.2277580000000007e+01  scaled by 1
```

**Comment by jgillis** [comment]
Isolated to `pow` instruction. Looks like the visual studio compiler computes power in a slightly different way than mingw.
This is not that unreasonable I suppose..
