### ISSUE TITLE
How to properly update the values of Opti().parameter

### ISSUE THREAD

**Issue by RandyChen233** [casadi/casadi#3244]
Hi all,

I am solving a consensus ADMM problem where I need to update the values of two different `parameter` variables at every iteration. The update of each parameter variable is dependent on the solution returned by `Opti().solve()`, which is the solution to my optimization sub-problem.

But I encountered the following error:

```

......


Process Process-61:
Process Process-63:
Process Process-62:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_321/2837594323.py", line 101, in run_worker
    d[f"opti_{agent_id}"].set_value(u, u + sol.value(states[f"Y_{agent_id}"]) - xbar)
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_321/2837594323.py", line 101, in run_worker
    d[f"opti_{agent_id}"].set_value(u, u + sol.value(states[f"Y_{agent_id}"]) - xbar)
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/site-packages/casadi/casadi.py", line 47680, in set_value
    return _casadi.Opti_set_value(self, *args)
  File "/tmp/ipykernel_321/2837594323.py", line 101, in run_worker
...
    set_value(self,[MX])
    set_value(self,MX,DM)
  You have: '(Opti,MX,MX)'

```

It seems like when I was using `set_value(parameter, value)` method to update the parameters, the solution returned by `Opti().solve()` is not a DM object, so I cannot pass that into `set_value( )`. How should I get around this?

I actually checked the data type returned by `Opti().solve()`, and I believe it's a numpy array by default

**Comment by jgillis** [comment]
`d[f"opti_{agent_id}"].set_value(u, sol.value(u+states[f"Y_{agent_id}"] - xbar))` perhaps?
