### ISSUE TITLE
`sqpmethod` fails if `proxqp` is used as qpsolver and the optimization problem contains equality and inequality constraints

### ISSUE THREAD

**Issue by GiulioRomualdi** [casadi/casadi#3319]
I tried to solve the `rocket.py` problem using `sqpmethod` via `proxqp`. To do that I modified the example with the following 
patch
```patch
diff --git a/docs/examples/python/rocket.py b/docs/examples/python/rocket.py
index 46dc7461f..41b726582 100644
--- a/docs/examples/python/rocket.py
+++ b/docs/examples/python/rocket.py
@@ -67,10 +67,11 @@ G = X[0:2]     # x(1:2) in Matlab
 
 # NLP
 nlp = {'x':U, 'f':J, 'g':G}
- 
+
 # Allocate an NLP solver
-opts = {"ipopt.tol":1e-10, "expand":True}
-solver = nlpsol("solver", "ipopt", nlp, opts)
+opts = {}
+opts["qpsol"] = "proxqp"
+solver = nlpsol("solver", "sqpmethod", nlp, opts)
 arg = {}
 
 # Bounds on u and initial condition
```

When I tried to solve the problem I got the following error:
```
python3 rocket.py 
-------------------------------------------
This is casadi::Sqpmethod.
Using exact Hessian
Number of variables:                              50
Number of constraints:                             2
Number of nonzeros in constraint Jacobian:       100
Number of nonzeros in Lagrangian Hessian:       2500

iter      objective    inf_pr    inf_du     ||d||  lg(rg) ls    info
   0   8.000000e+00  6.00e+00  8.00e-01  0.00e+00       -  0  - 
Function qpsol (0x55d0a399dc40)
Input 0 (h): 
[[2, 0, 0, ..., 0, 0, 0], 
 [0, 2, 0, ..., 0, 0, 0], 
 [0, 0, 2, ..., 0, 0, 0], 
 ...,
 [0, 0, 0, ..., 2, 0, 0], 
 [0, 0, 0, ..., 0, 2, 0], 
 [0, 0, 0, ..., 0, 0, 2]]
Input 1 (g): [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8]
Input 2 (a): 
[[1.34685, 1.30484, 1.26461, 1.22608, 1.18916, 1.15378, 1.11986, 1.08732, 1.05608, 1.02609, 0.997262, 0.969533, 0.942834, 0.917099, 0.892262, 0.868257, 0.84502, 0.822486, 0.800593, 0.779275, 0.758468, 0.738108, 0.718131, 0.698469, 0.679057, 0.659826, 0.640707, 0.621629, 0.602519, 0.583301, 0.563898, 0.544229, 0.524209, 0.50375, 0.482761, 0.461144, 0.438798, 0.415615, 0.391482, 0.366276, 0.339871, 0.312129, 0.282905, 0.252041, 0.219371, 0.184716, 0.147883, 0.108664, 0.0668364, 0.0221595], 
 [0.0462322, 0.0461785, 0.0461795, 0.0462367, 0.0463516, 0.0465262, 0.0467625, 0.047063, 0.0474302, 0.0478671, 0.048377, 0.0489633, 0.04963, 0.0503814, 0.051222, 0.0521571, 0.053192, 0.0543329, 0.0555862, 0.0569591, 0.0584594, 0.0600952, 0.0618757, 0.0638108, 0.0659109, 0.0681876, 0.0706533, 0.0733215, 0.0762067, 0.0793247, 0.0826925, 0.0863286, 0.0902528, 0.0944867, 0.0990538, 0.103979, 0.10929, 0.115017, 0.12119, 0.127846, 0.135022, 0.142758, 0.151098, 0.160091, 0.169788, 0.180246, 0.191525, 0.203692, 0.216818, 0.230983]]
Input 3 (lba): [-6.00128, -2.58098]
Input 4 (uba): [-6.00128, -2.58098]
Input 5 (lbx): [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9]
Input 6 (ubx): [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
Input 7 (x0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Input 8 (lam_x0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Input 9 (lam_a0): [0, 0]
Input 10 (q): NULL
Input 11 (p): NULL
Traceback (most recent call last):
  File "/home/gromualdi/robot-code/robotology-superbuild/src/casadi/docs/examples/python/rocket.py", line 87, in <module>
    res = solver(**arg)
  File "/home/gromualdi/robot-code/robotology-superbuild/build/install/lib/python3/dist-packages/casadi/casadi.py", line 10683, in __call__
    return self.call(kwargs)
  File "/home/gromualdi/robot-code/robotology-superbuild/build/install/lib/python3/dist-packages/casadi/casadi.py", line 9212, in call
    return _casadi.Function_call(self, *args)
RuntimeError: Error in Function::call for 'solver' [Sqpmethod] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'solver' [Sqpmethod] at .../casadi/core/function.cpp:330:
Error in Function::operator() for 'qpsol' [ProxqpInterface] at .../casadi/core/function.cpp:1482:
From file: /home/gromualdi/robot-code/robotology-superbuild/build/install/include/proxsuite/proxqp/sparse/wrapper.hpp
in function: void proxsuite::proxqp::sparse::QP<T, I>::init(proxsuite::optional<Eigen::SparseMatrix<Scalar, 0, StorageIndex> >, proxsuite::optional<Eigen::Ref<const Eigen::Matrix<Type, -1, 1> > >, proxsuite::optional<Eigen::SparseMatrix<Scalar, 0, StorageIndex> >, proxsuite::optional<Eigen::Ref<const Eigen::Matrix<Type, -1, 1> > >, proxsuite::optional<Eigen::SparseMatrix<Scalar, 0, StorageIndex> >, proxsuite::optional<Eigen::Ref<const Eigen::Matrix<Type, -1, 1> > >, proxsuite::optional<Eigen::Ref<const Eigen::Matrix<Type, -1, 1> > >, bool, proxsuite::optional<T>, proxsuite::optional<T>, proxsuite::optional<T>) [with T = double; I = long long int; proxsuite::optional<Eigen::SparseMatrix<Scalar, 0, StorageIndex> > = std::optional<Eigen::SparseMatrix<double, 0, long long int> >; proxsuite::optional<Eigen::Ref<const Eigen::Matrix<Type, -1, 1> > > = std::optional<Eigen::Ref<const Eigen::Matrix<double, -1, 1>, 0, Eigen::InnerStride<1> > >; typename Eigen::internal::conditional<const Eigen::Matrix<Type, -1, 1>::IsVectorAtCompileTime, Eigen::InnerStride<1>, Eigen::OuterStride<> >::type = Eigen::InnerStride<1>; proxsuite::optional<T> = std::optional<double>]
at line: 234
wrong argument size: expected 50, got 100
hint: the column dimension for initializing A is not valid.
```

If I try to use `osqp` as qp solver, I get the correct result (the same as ipopt).

Looking at the code I found some possible issues in `proxqp_interface.cpp`. I'm going to open an PR with a possible bugfix

I'm using the following commit 896ebb1083311cfdb392f411ba83385080a05ed3

**Comment by GiulioRomualdi** [comment]
Associated PR: https://github.com/casadi/casadi/issues/3320

**Comment by charleskhazoom** [comment]
related to #3205
