### ISSUE TITLE
Debugging py3.12 crash

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3448]
`conda create --name py312dbg -c conda-forge/label/python_debug -c conda-forge/label/main python=3.12=h95cd788_0_debug_cpython`

python function.py Functiontests.test_map_exception

**Comment by jgillis** [comment]
```
#0  0x00005555558a04f0 in _PyErr_GetRaisedException (tstate=0x0) at /usr/local/src/conda/python-3.12.0/Python/errors.c:490
#1  0x0000555555910f1e in sys_write (key=0x555555ce6a08 <_PyRuntime+74472>, fp=0x7ffff7e155c0 <_IO_2_1_stderr_>, format=0x7fffcd121acc "%.*s", va=0x7fffb62da580) at /usr/local/src/conda/python-3.12.0/Python/sysmodule.c:3817
#2  0x00005555559111f0 in PySys_WriteStderr (format=0x7fffcd121acc "%.*s") at /usr/local/src/conda/python-3.12.0/Python/sysmodule.c:3848
#3  0x00007fffcce28002 in casadi::pythonlogger (s=0x7fffccb0dedc "Function ", num=9, error=true) at /work/swig/python/target3/source/casadiPYTHON_wrap.cxx:3778
#4  0x00007fffcc56b7be in casadi::Logger::WriteFunThreadSafe (s=0x7fffccb0dedc "Function ", num=9, error=true) at /work/casadi/core/casadi_logger.cpp:46
#5  0x00007fffcc56c210 in casadi::Logger::write<true> (s=0x7fffccb0dedc "Function ", num=9) at /work/casadi/core/casadi_logger.hpp:84
#6  0x00007fffcc56c135 in casadi::Logger::Streambuf<true>::xsputn (this=0x7fffccd192e8 <casadi::uerr()::instance+8>, s=0x7fffccb0dedc "
```

**Comment by jgillis** [comment]
Probably introduced in https://github.com/python/cpython/commit/4c87537efb5fd28b4e4ee9631076ed5953720156#diff-a3a5c73931235f7f344c072dc755d6508e13923db3f5d581c5e88652075871cbR3665

**Comment by jgillis** [comment]
It was because we were not holding the GIL. Disabling outside the main thread for now..
