### ISSUE TITLE
Symmetric jacobian with MX

### ISSUE THREAD

**Issue by FreyJo** [casadi/casadi#3703]
Hi,

There is an issue with symmetric Jacobian with `MX` symbolics.
A minimal example to reproduce the issue:
```
import casadi as ca
x = ca.MX.sym('x', 4)
u = ca.MX.sym('u', 2)

h = x[1]*5*x[2]

nh = 1
lam_h = ca.MX.sym('lam_h', nh, 1)

adj_ux = ca.jtimes(h, ca.vertcat(u, x), lam_h, True)
hess_ux = ca.jacobian(adj_ux, ca.vertcat(u, x), {'symmetric': True})
```

I get the following error:

....
CasADi - 2024-05-21 13:55:09 MESSAGE("StarColoring requires a square matrix, got 4x6.") [.../casadi/core/sparsity_internal.cpp:3292]
Traceback (most recent call last):
  File ".../mini_test.py", line 11, in <module>
    hess_ux = ca.jacobian(adj_ux, ca.vertcat(u, x), {'symmetric': True})
  File ".../casadi.py", line 36836, in jacobian
    return _casadi.jacobian(*args)
RuntimeError: Error in MX::jacobian at .../casadi/core/mx.cpp:1708:
Error in XFunction::jac for 'helper_jacobian_MX' [MXFunction] at .../casadi/core/x_function.hpp:804:
.../casadi/core/sparsity_internal.cpp:3476: Assertion "p.size()==size1()" failed:
Notify the CasADi developers.

Note that this does not occur when defining `h` as `h = u[1]*5*x[2]` or when using `SX` symbolics.
Related to https://github.com/acados/acados/pull/1117

**Comment by jgillis** [comment]
The problem is that 'symmetric' option is silently assuming a dense input.
```
import casadi as ca
x = ca.MX.sym('x', 4)
u = ca.MX.sym('u', 2)

h = x[1]*5*x[2]

nh = 1
lam_h = ca.MX.sym('lam_h', nh, 1)

adj_ux = ca.densify(ca.jtimes(h, ca.vertcat(u, x), lam_h, True))
hess_ux = ca.jacobian(adj_ux, ca.vertcat(u, x), {'symmetric': True})
```

This may or may not be cheaper than default symmetric False due to lack of #172
