### ISSUE TITLE
Installation error on TX2

### ISSUE THREAD

**Issue by jakdoonga** [casadi/casadi#3802]
I'm trying to install casadi library without pip on Jetson TX2 with python 3.6.9

so I downloaded the tar.gz. file which version is 3.5.5
and I unzip it and do the below example on casadi-get website

from sys import path
path.append(r"<yourpath>/casadi-py36-v3.5.5")
from casadi import *
x = MX.sym("x")

when I run above code, and I got below errors

>>> import casadi

Traceback (most recent call last):
  File "/home/nvidia/Downloads/casadi/casadi.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/nvidia/Downloads/casadi/_casadi.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/Downloads/casadi/__init__.py", line 36, in <module>
    from casadi.casadi import *
  File "/home/nvidia/Downloads/casadi/casadi.py", line 21, in <module>
    _casadi = swig_import_helper()
  File "/home/nvidia/Downloads/casadi/casadi.py", line 20, in swig_import_helper
    return importlib.import_module('_casadi')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_casadi'

Thank you for your kind replies

**Comment by tmmsartor** [comment]
First of all it is possible to download also latest casadi version 3.6.6 without pip, you want to use that, this by visiting the "Assets" section of the given release. I.e. by going to https://github.com/casadi/casadi/releases/tag/3.6.6 and scrolling at the bottom of the page.

If you downloaded `tar.gz` archive it should get the source of the given version, which mean you don't have compiled libraries thus no `_casadi.so` is present.


What you can download is the zip file for the right combination of python version and os/cpu_architecture,
which in your case would be I guess this file: [casadi-3.6.6-linux-aarch64-py36](https://github.com/casadi/casadi/releases/download/3.6.6/casadi-3.6.6-linux-aarch64-py36.zip) (Assuming your are running 64bit Linux OS)

So you can try to run:
```bash
wget https://github.com/casadi/casadi/releases/download/3.6.6/casadi-3.6.6-linux-aarch64-py36.zip
unzip casadi-3.6.6-linux-aarch64-py36.zip -d casadi-3.6.6-linux-aarch64-py36
python -c "import sys; sys.path=['casadi-3.6.6-linux-aarch64-py36']+sys.path; import casadi; print(casadi.__file__)"
```

NB: Given that from your error, it seems your script is trying to import casadi from the local folder or anyway another path different from the you specified, in the above code I made sure to prioritize the fresh downloaded version of casadi.

**Comment by jakdoonga** [comment]
Thanks for your kind reply
I was busy that I checked your reply late.
I actually replace my wifi module and download casadi library online and my problem is solved
I will try your suggestion when I get through similar error in future.
Again thank you!
