### ISSUE TITLE
Error in loading Gurobi adaptor with Gurobi v12.0.0

### ISSUE THREAD

**Issue by FilippoAiraldi** [casadi/casadi#3927]
Hey guys, 

thanks for the great work and the great tool. I wanted to share an issue that I encountered with the latest Gurobi optimizer, hope it is helpful.

Cheers,
Filippo

System: Ubuntu 24.04.1
Python: 3.12.5
casadi: 3.6.7

I installed both Gurobi v11.0.3 and v12.0.0 on a Ubuntu machine, and set the corresponding environment variables so that I could then call either as a plugin, i.e.,
```bash
export GUROBI_VERSION=110  # or 120
export GUROBI_HOME=path/to/gurobi110/linux64  # or path/to/gurobi120/linux64
export PATH=$GUROBI_HOME/bin:$PATH
export LD_LIBRARY_PATH=$GUROBI_HOME/lib:$LD_LIBRARY_PATH
```
I then wrote the small test below:
```python
from casadi import Opti

opti = Opti("conic")
x = opti.variable()
opti.minimize((x - 1) * x)
opti.subject_to(x >= 3)
opti.solver("gurobi")
opti.solve()
```
When using Gurobi v11.0.3, everything works fine. When instead v12.0.0 is used, I got the following error:
```
CasADi - 2024-11-19 23:32:43 WARNING("Failed to load Gurobi adaptor: Could not find symbol 'GRBloadenv' in libgurobi120.so.") [.../casadi/interfaces/gurobi/gurobi_interface.cpp:45]
CasADi - 2024-11-19 23:32:43 WARNING(".../casadi/core/plugin_interface.hpp:170: Assertion "flag==0" failed:
Registration of plugin failed.") [.../casadi/core/plugin_interface.hpp:142]
Traceback (most recent call last):
  File "/home/fairaldi/gurobi_test.py", line 8, in <module>
    opti.solve()
  File "/home/fairaldi/bin/miniconda3/envs/py312/lib/python3.12/site-packages/casadi/casadi.py", line 48364, in solve
    return _casadi.Opti_solve(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:165:
.../casadi/core/plugin_interface.hpp:292: Plugin 'gurobi' is not found.
```

**Comment by polcrub** [comment]
In the case of Mac, using VS Code, I got Gurobi v12 to work with CasADi 3.7.0 after 4 hours by modifying the .bash_profile file located at "/Users/<my user>" folder adding the following: 
```
export GUROBI_VERSION=100
export GUROBI_HOME=/Library/gurobi1201/macos_universal2
export PATH=$GUROBI_HOME/bin:$PATH
export LD_LIBRARY_PATH=$GUROBI_HOME/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/usr/local/lib
export GRB_LICENSE_FILE=/Users/<YOUR USER>/gurobi.lic
```

Moreover, you have to go the /usr/local/lib folder and modify the whatever libgurobi<VERSION>.dylib alias file you have to the specific `libgurobi100.dylib` filename. That is the only way I found it to work with VS Code and my virtual Python environment in Mac. On the contrary, using Spyder 6 IDE I only remember to have had to add the `export GUROBI_VERSION=100 ` to the .bashrc file of my user folder. This could be so easily explained in a post from CasADi or just automated assuming the default GUROBI installation path.
